# Sports Analytics - Project 1

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# read file
sports = pd.read_excel('C:\\Users\\seanj\\Desktop\\Sports Analytics\\Project\\Fandom Survey Beta student.xlsx')

In [3]:
# display all columns
pd.set_option('max_columns', None)
pd.set_option('max_rows', 10)

In [4]:
# check file
sports.head()

,Progress,Duration (in seconds),Finished,Q2,Q3_NPS_GROUP,Q3,Q4_NPS_GROUP,Q4,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q8,Q9_1,Q9_2,Q9_3,Q9_4,Q10_1,Q10_2,Q10_3,Q11_1,Q12_1,Q13_1,Q13_2,Q14_1,Q14_2,Q14_3,Q15_1,Q15_2,Q15_3,Q15_4,Q16_1,Q16_2,Q16_3,Q16_4,Q16_5,Q16_6,Q16_7,Q16_8,Q17_1,Q17_2,Q17_3,Q17_4,Q17_5,Q17_6,Q17_7,Q17_8,Q17_9,Q17_10,Q18_1,Q18_2,Q18_3,Q18_4,Q18_5,Q18_6,Q18_7,Q18_8,Q19_1,Q19_2,Q19_3,Q19_4,Q20_1,Q20_2,Q20_3,Q20_4,Q20_5,Q20_6,Q20_7,Q21_1,Q21_2,Q21_3,Q21_4,Q21_5,Q22,Q23,Q24,Q25,Q26_1,Q26_2,Q27,Q28#1_1,Q28#1_2,Q28#1_3,Q28#1_4,Q28#1_5,Q28#1_6,Q28#1_7,Q28#1_8,Q28#1_9,Q28#1_10,Q28#1_11,Q28#1_12,Q28#1_13,Q28#1_14,Q28#1_15,Q28#1_16,Q28#1_17,Q28#1_18,Q28#1_19,Q28#1_20,Q28#1_21,Q28#1_22,Q28#1_23,Q28#1_24,Q28#1_25,Q28#1_26,Q28#1_27,Q28#1_28,Q28#1_29,Q28#1_30,random
0,Progress,Duration (in seconds),Finished,What is your favorite sports team?,"On a scale from 0-10, to what degree do you co...","On a scale from 0-10, to what degree do you co...","On a scale from 0-10, to what degree do you co...","On a scale from 0-10, to what degree do you co...",Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best indicat...,Please indicate the response that best indicat...,Please indicate the response that best indicat...,Please indicate the response that best indicat...,Please indicate the response that best indicat...,Please indicate the response that best indicat...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,How much are you willing to spend on a single ...,Please indicate - How likely you are to: - Att...,Please indicate - How likely you are to: - Wat...,Please indicate - How likely you are to: - Wat...,Please indicate - How likely you are to: - Vie...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,"When attending a live event, how much of the e...",When watching a live event on television or so...,Please indicate the response that best describ...,Please indicate the response that best describ...,"When using a second screen, do you use it for ...","When using a second screen, do you use it for ...","When using a second screen, do you use it for ...",Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,Please indicate the response that best describ...,How important are the following factors for yo...,How important are the following factors for yo...,How important are the following factors for yo...,How important are the following factors for yo...,How important are the following factors for yo...,How important are the following factors for yo...,How important are the following factors for yo...,How important are the following factors for yo...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,Do you consider yourself to be a fan of follow...,"To what degree, do you feel you share similari...","To what degree, do you feel you share similari...","To what degree, do you feel you share similari...","To what degree, do you feel you share similari...","To what degree, do you feel you share similari...","To what degree, do you feel you share similari...","To what degree, do you feel you share similari...","To what degree, do you feel you share similari...",Please use the slider to rate your agreement w...,Please use the slider to rate your agreement w...,Please use the slider to rate your agreement w...,Please use the slider to rate your agreement w...,Please select the response that best describes...,Please select the response that best describes...,Please select the response that best describes...,Please select the response that best describes...,Please select the response that best describes...,Please select the response that best describes...,Please select the response that best describes...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please indicate your age in years,What is your gender?,Which racial group do you belong?,Please indicate the choice that best describes...,Please choose the response that best describes...,Please choose the response that best describes...,What is your nationality?,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,Are you a fan of the listed individual or simi...,random
1,100,129,1,phoenix suns,1,4,1,6,3,2,3,4,5,4,4,4,3,3,4,4,5,5,3,2,1,3,2,3,20,2,4,4,4,3,3,3,39,29,5,4,50,50,0,5,3,4,3,4,2,3,4,4,4,4,5,2,3,4,3,5,4,4,5,4,4,3,2,4,3,4,4,4,4,36,42,35,36,27,58,40,56,42,49,36,2,3,2,5,4,27,1,1,2,4,4,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,6965
2,100,314,1,Dallas Cowboys,1,6,1,1,6,6,1,1,6,5,1,1,6,6,4,4,6,6,4,4,3,3,5,3,500,5,7,6,5,3,1,1,100,100,5,5,20,80,0,6,6,6,6,6,6,6,6,6,6,6,6,6,6,3,3,3,3,3,3,3,3,2,2,6,6,6,6,2,4,1,0,0,0,73,73,75,81,75,5,1,5,5,5,5,5,52,1,1,3,5,3,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,7540
3,100,309,1,Green Bay Packers,3,10,3,9,7,1,5,3,2,1,2,2,5,4,6,3,4,5,4,4,5,5,5,5,125,7,7,5,6,3,2,2,99,92,2,4,15,25,60,2,2,4,6,4,6,5,3,2,2,1,1,7,5,5,6,4,2,3,2,1,1,5,4,6,6,4,5,7,4,91,95,99,60,83,13,76,83,90,72,80,5,7,2,3,4,39,1,1,1,2,3,1,2,1,2,2,2,2,2,1,2,1,1,2,2,2,2,1,2,1,2,2,2,2,2,2,1,2,2,2,2,1,4052
4,100,385,1,Saints,2,7,1,6,7,7,3,2,5,7,4,6,7,7,5,4,7,5,5,5,4,4,5,5,2,2,6,7,5,3,1,1,59,81,6,6,0,100,0,4,5,5,7,5,4,6,7,7,7,5,5,7,7,7,7,7,5,5,5,1,3,4,3,6,5,7,5,3,6,2,3,1,3,100,100,49,28,5,35,17,7,5,7,6,2,28,1,2,1,4,7,1,1,2,2,2,1,1,1,2,2,1,1,1,1,1,1,2,1,2,2,2,1,1,1,1,1,2,2,2,1,2,3364

In [5]:
# info
sports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Columns: 127 entries, Progress to random
dtypes: object(127)
memory usage: 359.3+ KB

In [6]:
# shape
sports.shape

(362, 127)

In [7]:
# data type
sports.dtypes

Progress                 object
Duration (in seconds)    object
Finished                 object
Q2                       object
Q3_NPS_GROUP             object
                          ...
Q28#1_27                 object
Q28#1_28                 object
Q28#1_29                 object
Q28#1_30                 object
random                   object
Length: 127, dtype: object

In [8]:
# descriptive stats
sports.describe()

,Progress,Duration (in seconds),Finished,Q2,Q3_NPS_GROUP,Q3,Q4_NPS_GROUP,Q4,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q8,Q9_1,Q9_2,Q9_3,Q9_4,Q10_1,Q10_2,Q10_3,Q11_1,Q12_1,Q13_1,Q13_2,Q14_1,Q14_2,Q14_3,Q15_1,Q15_2,Q15_3,Q15_4,Q16_1,Q16_2,Q16_3,Q16_4,Q16_5,Q16_6,Q16_7,Q16_8,Q17_1,Q17_2,Q17_3,Q17_4,Q17_5,Q17_6,Q17_7,Q17_8,Q17_9,Q17_10,Q18_1,Q18_2,Q18_3,Q18_4,Q18_5,Q18_6,Q18_7,Q18_8,Q19_1,Q19_2,Q19_3,Q19_4,Q20_1,Q20_2,Q20_3,Q20_4,Q20_5,Q20_6,Q20_7,Q21_1,Q21_2,Q21_3,Q21_4,Q21_5,Q22,Q23,Q24,Q25,Q26_1,Q26_2,Q27,Q28#1_1,Q28#1_2,Q28#1_3,Q28#1_4,Q28#1_5,Q28#1_6,Q28#1_7,Q28#1_8,Q28#1_9,Q28#1_10,Q28#1_11,Q28#1_12,Q28#1_13,Q28#1_14,Q28#1_15,Q28#1_16,Q28#1_17,Q28#1_18,Q28#1_19,Q28#1_20,Q28#1_21,Q28#1_22,Q28#1_23,Q28#1_24,Q28#1_25,Q28#1_26,Q28#1_27,Q28#1_28,Q28#1_29,Q28#1_30,random
count,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362,362
unique,2,267,2,238,4,12,4,12,8,8,8,8,8,8,8,8,7,8,8,8,8,8,6,6,6,6,6,6,47,8,8,8,8,8,8,8,61,76,8,8,24,24,18,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,83,81,93,90,71,94,87,91,92,90,94,8,8,8,8,8,57,5,7,5,8,8,5,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,351
top,100,421,1,New York Yankees,2,10,1,10,7,1,1,1,1,1,1,1,7,7,7,4,7,6,5,1,5,5,5,5,50,7,7,7,7,1,1,1,100,100,1,1,0,0,0,1,5,1,6,5,6,5,7,5,5,1,1,7,7,5,7,5,1,1,5,1,1,5,5,7,4,4,5,4,1,0,0,0,0,100,100,100,100,0,0,0,6,7,5,5,1,32,1,1,1,7,7,1,1,2,2,2,2,2,1,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,2,2,2,5725
freq,361,4,361,8,125,74,171,54,107,69,80,111,127,177,149,105,192,144,87,92,90,79,114,88,121,104,142,120,56,87,170,99,96,130,191,230,159,83,114,83,143,94,211,100,69,86,93,85,83,89,97,70,71,91,84,133,115,69,96,73,132,105,65,138,96,92,80,103,93,86,86,90,79,78,72,50,59,91,47,34,48,31,39,52,115,124,99,100,69,22,186,263,144,77,116,358,184,271,213,273,202,254,187,239,266,229,207,260,219,199,216,228,237,237,259,286,218,222,219,197,203,299,326,301,192,276,2

In [9]:
# drop questions
sports_v1 = sports.drop(0)

In [10]:
# check file
sports_v1

,Progress,Duration (in seconds),Finished,Q2,Q3_NPS_GROUP,Q3,Q4_NPS_GROUP,Q4,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q8,Q9_1,Q9_2,Q9_3,Q9_4,Q10_1,Q10_2,Q10_3,Q11_1,Q12_1,Q13_1,Q13_2,Q14_1,Q14_2,Q14_3,Q15_1,Q15_2,Q15_3,Q15_4,Q16_1,Q16_2,Q16_3,Q16_4,Q16_5,Q16_6,Q16_7,Q16_8,Q17_1,Q17_2,Q17_3,Q17_4,Q17_5,Q17_6,Q17_7,Q17_8,Q17_9,Q17_10,Q18_1,Q18_2,Q18_3,Q18_4,Q18_5,Q18_6,Q18_7,Q18_8,Q19_1,Q19_2,Q19_3,Q19_4,Q20_1,Q20_2,Q20_3,Q20_4,Q20_5,Q20_6,Q20_7,Q21_1,Q21_2,Q21_3,Q21_4,Q21_5,Q22,Q23,Q24,Q25,Q26_1,Q26_2,Q27,Q28#1_1,Q28#1_2,Q28#1_3,Q28#1_4,Q28#1_5,Q28#1_6,Q28#1_7,Q28#1_8,Q28#1_9,Q28#1_10,Q28#1_11,Q28#1_12,Q28#1_13,Q28#1_14,Q28#1_15,Q28#1_16,Q28#1_17,Q28#1_18,Q28#1_19,Q28#1_20,Q28#1_21,Q28#1_22,Q28#1_23,Q28#1_24,Q28#1_25,Q28#1_26,Q28#1_27,Q28#1_28,Q28#1_29,Q28#1_30,random
1,100,129,1,phoenix suns,1,4,1,6,3,2,3,4,5,4,4,4,3,3,4,4,5,5,3,2,1,3,2,3,20,2,4,4,4,3,3,3,39,29,5,4,50,50,0,5,3,4,3,4,2,3,4,4,4,4,5,2,3,4,3,5,4,4,5,4,4,3,2,4,3,4,4,4,4,36,42,35,36,27,58,40,56,42,49,36,2,3,2,5,4,27,1,1,2,4,4,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,6965
2,100,314,1,Dallas Cowboys,1,6,1,1,6,6,1,1,6,5,1,1,6,6,4,4,6,6,4,4,3,3,5,3,500,5,7,6,5,3,1,1,100,100,5,5,20,80,0,6,6,6,6,6,6,6,6,6,6,6,6,6,6,3,3,3,3,3,3,3,3,2,2,6,6,6,6,2,4,1,0,0,0,73,73,75,81,75,5,1,5,5,5,5,5,52,1,1,3,5,3,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,7540
3,100,309,1,Green Bay Packers,3,10,3,9,7,1,5,3,2,1,2,2,5,4,6,3,4,5,4,4,5,5,5,5,125,7,7,5,6,3,2,2,99,92,2,4,15,25,60,2,2,4,6,4,6,5,3,2,2,1,1,7,5,5,6,4,2,3,2,1,1,5,4,6,6,4,5,7,4,91,95,99,60,83,13,76,83,90,72,80,5,7,2,3,4,39,1,1,1,2,3,1,2,1,2,2,2,2,2,1,2,1,1,2,2,2,2,1,2,1,2,2,2,2,2,2,1,2,2,2,2,1,4052
4,100,385,1,Saints,2,7,1,6,7,7,3,2,5,7,4,6,7,7,5,4,7,5,5,5,4,4,5,5,2,2,6,7,5,3,1,1,59,81,6,6,0,100,0,4,5,5,7,5,4,6,7,7,7,5,5,7,7,7,7,7,5,5,5,1,3,4,3,6,5,7,5,3,6,2,3,1,3,100,100,49,28,5,35,17,7,5,7,6,2,28,1,2,1,4,7,1,1,2,2,2,1,1,1,2,2,1,1,1,1,1,1,2,1,2,2,2,1,1,1,1,1,2,2,2,1,2,3364
5,100,357,1,New Orleans Saints,3,9,3,10,7,7,5,4,3,7,2,1,5,6,7,6,5,7,4,5,4,4,4,5,400,5,6,6,6,6,3,2,62,72,5,6,10,90,0,2,5,4,3,5,6,7,6,6,6,7,6,5,6,7,6,5,6,6,6,5,6,5,6,7,6,6,6,7,6,71,73,85,93,61,70,70,89,100,100,71,6,6,7,6,5,29,2,1,3,3,2,1,1,2,1,2,1,2,2,2,1,2,1,2,2,2,1,2,2,2,1,2,1,1,1,2,2,1,2,1,2,2,6711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,100,513,1,Mavericks,1,3,1,3,2,6,2,1,5,1,2,2,6,6,4,2,5,7,1,1,1,2,3,3,35,4,5,2,6,1,1,1,100,70,5,2,20,80,0,6,7,2,7,6,6,5,7,5,6,1,2,5,7,5,7,2,1,1,3,1,1,5,5,3,4,3,2,1,2,40,10,80,20,90,10,40,20,20,80,90,1,2,2,5,7,22,2,1,1,6,6,1,1,2,2,1,2,2,1,2,2,1,2,2,1,1,2,2,2,1,2,1,1,2,1,1,1,2,2,2,2,2,4748
358,100,402,1,none,1,0,1,0,1,1,1,1,4,6,1,1,5,4,5,4,7,7,3,2,3,4,3,3,50,4,3,5,5,5,4,5,28,48,3,4,5,95,0,4,4,5,6,4,5,6,5,5,6,4,5,7,7,1,1,1,4,1,1,1,1,5,4,4,4,3,5,4,4,16,55,32,32,22,39,50,20,28,79,17,6,4,5,4,4,22,2,3,1,4,4,1,1,2,2,2,2,2,1,2,2,1,1,2,2,1,1,2,2,2,2,1,2,2,1,2,2,1,2,2,2,2,5708
359,100,302,1,University of Alabama,2,7,2,7,7,1,5,2,3,1,1,1,7,1,7,1,4,4,5,5,5,5,5,5,50,7,7,7,7,1,1,1,100,85,1,7,50,50,0,3,7,3,4,4,4,4,4,4,4,4,4,3,4,2,7,5,5,7,7,1,7,7,7,7,1,5,5,3,4,100,100,100,100,100,1,100,100,100,100,100,7,5,5,6,6,27,2,1,1,4,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,1,1,1,2,2,2,2,2,1317
360,100,588,1,New Orleans Saints,1,5,2,7,6,1,4,1,3,1,1,1,7,6,6,3,3,2,5,2,5,5,3,4,50,3,7,5,6,5,1,1,81,52,3,5,35,45,20,1,4,4,7,7,5,5,7,3,5,4,4,7,7,5,4,5,2,2,4,1,1,3,4,5,4,1,5,3,4,0,29,62,61,51,100,1,42,0,86,72,7,5,5,7,3,27,2,5,2,4,3,1,2,2,1,2,2,1,2,2,2,2,2,2,2,1,2,2,1,1,1,2,2,1,1,1,2,2,2,1,2,1,3189
361,100,383,1,New York Yankees,1,0,1,0,1,1,1,1,1,6,4,5,4,5,6,4,4,6,1,1,3,3,2,3,25,1,4,4,5,1,1,1,100,90,1,1,0,0,100,4,5,6,5,4,4,6,7,3,3,4,6,7,7,6,5,5,6,2,6,5,2,4,4,6,5,5,6,6,6,10,10,10,10,75,65,65,75,75,65,80,6,6,4,6,4,26,1,1,2,6,7,1,2,2,2,2,1,2,2,2,2,2,2,2,2,1,2,1,2,2,2,2,1,1,1,2,1,2,2,2,1,2,1126

In [11]:
# make copy of file
sports_v2 = sports.copy()

In [12]:
# Cleaning team names by removing full stop
sports_v2['Q2'] = sports_v2['Q2'].str.lower().str.strip().str.replace(".", "")

C:\Users\seanj\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.

In [13]:
# create team variables
teams = sports_v2['Q2'][1:].unique()

In [14]:
# number of unique teams
sports_v2['Q2'].nunique()

190

In [15]:
# check all teams
sports_v2['Q2'].value_counts(sort=True)
pd.set_option('max_rows', None)
sports_v2['Q2'].value_counts(sort=True)

new york yankees                                                                                                          13
yankees                                                                                                                    9
lakers                                                                                                                     8
green bay packers                                                                                                          8
none                                                                                                                       7
dallas cowboys                                                                                                             7
cleveland browns                                                                                                           7
chicago cubs                                                                                                               7
chicago bears                                                                                                              7
new england patriots                                                                                                       7
pittsburgh steelers                                                                                                        6
eagles                                                                                                                     6
atlanta braves                                                                                                             5
new orleans saints                                                                                                         5
steelers                                                                                                                   4
giants                                                                                                                     4
seahawks                                                                                                                   4
buffalo bills                                                                                                              4
san francisco 49ers                                                                                                        4
manchester united                                                                                                          4
houston astros                                                                                                             4
miami heat                                                                                                                 4
kansas city chiefs                                                                                                         4
tennessee titans                                                                                                           3
packers                                                                                                                    3
warriors                                                                                                                   3
new york jets                                                                                                              3
san antonio spurs                                                                                                          3
baltimore ravens                                                                                                           3
seattle seahawks                                                                                                           3
dallas mavericks                                                                                                           3
pittsburgh penguins                                                                                                        3
detroit lions                                                                                                              3
chicago bulls                                                                                                              3
cricket                                                                                                                    3
st louis blues                                                                                                             2
washington wizards                                                                                                         2
kc chiefs                                                                                                                  2
ravens                                                                                                                     2
cleveland indians                                                                                                          2
los angeles lakers                                                                                                         2
tennis                                                                                                                     2
new york mets                                                                                                              2
milwaukee bucks                                                                                                            2
charlotte hornets                                                                                                          2
detroit red wings                                                                                                          2
golden state warriors                                                                                                      2
phoenix suns                                                                                                               2
phillies                                                                                                                   2
st louis cardinals                                                                                                         2
texas rangers                                                                                                              2
boston celtics                                                                                                             2
mavericks                                                                                                                  2
patriots                                                                                                                   2
jets                                                                                                                       2
chicago blackhawks                                                                                                         2
red sox                                                                                                                    2
new jersey devils                                                                                                          2
cardinals                                                                                                                  2
reds                                                                                                                       2
raiders                                                                                                                    2
houston texans                                                                                                             2
colorado avalanche                                                                                                         2
las vegas raiders                                                                                                          2
barcelona                                                                                                                  2
football                                                                                                                   2
ny yankees                                                                                                                 2
la lakers                                                                                                                  2
denver broncos                                                                                                             1
tampa bay rays                                                                                                             1
as team                                                                                                                    1
what is your favorite sports team?                                                                                         1
florida state seminoles                                                                                                    1
nfl team                                                                                                                   1
chelsea                                                                                                                    1
los angels dodgers                                                                                                         1
i don't watch sports                                                                                                       1
cleveland cavaliers                                                                                                        1
kentucky wildcats                                                                                                          1
columbus blue jackets                                                                                                      1
twins                                                                                                                      1
tampa bucs                                                                                                                 1
detroit pistons                                                                                                            1
edmonton oilers                                                                                                            1
utah jazz                                                                                                                  1
padres                                                                                                                     1
montreal canadian hockey team                                                                                              1
los angeles kings                                                                                                          1
the bulls                                                                                                                  1
broncos                                                                                                                    1
la kings                                                                                                                   1
brewers                                                                                                                    1
juventus fc                                                                                                                1
fff                                                                                                                        1
pittsburgh pirates                                                                                                         1
the lakers                                                                                                                 1
mlb                                                                                                                        1
liverpool fc                                                                                                               1
hendrick motor sports                                                                                                      1
samsung white                                                                                                              1
villanova wildcats                                                                                                         1
philadelphia phillies                                                                                                      1
anaheim angels                                                                                                             1
austrlia                                                                                                                   1
columbus clippers                                                                                                          1
chicago white sox                                                                                                          1
cowboys                                                                                                                    1
new york knicks                                                                                                            1
rockets                                                                                                                    1
miami marlins                                                                                                              1
atlanta hawks                                                                                                              1
jacksonville jaguars                                                                                                       1
arkansas razorbacks                                                                                                        1
aggies                                                                                                                     1
oklahoma state cowboys                                                                                                     1
detroit tigers                                                                                                             1
criket                                                                                                                     1
bulls                                                                                                                      1
tampa bay bucaneers                                                                                                        1
ou sooners                                                                                                                 1
basketball                                                                                                                 1
nashville predators                                                                                                        1
vegas golden knights                                                                                                       1
cleveland cavs                                                                                                             1
new york islanders                                                                                                         1
sport, team/player baseball, new york yankees football, new york giants basketball, new york knicks hockey, new jersey     1
brooklyn nets                                                                                                              1
capitals                                                                                                                   1
chargers                                                                                                                   1
atlanta falcons                                                                                                            1
philadelphia flyers                                                                                                        1
university of alabama                                                                                                      1
dodgers                                                                                                                    1
ndsu bison                                                                                                                 1
softball                                                                                                                   1
washington nats                                                                                                            1
colts                                                                                                                      1
ball                                                                                                                       1
laker                                                                                                                      1
michigan wolverines                                                                                                        1
wildcats                                                                                                                   1
badgers                                                                                                                    1
saints if husband is watching                                                                                              1
dallas stars                                                                                                               1
georgia bulldogs                                                                                                           1
miami hurricanes                                                                                                           1
dolfins                                                                                                                    1
indiana pacers                                                                                                             1
houston rockets                                                                                                            1
fc dallas                                                                                                                  1
pittsburgh pinguins                                                                                                        1
purdue university basketball                                                                                               1
nbl                                                                                                                        1
redsox                                                                                                                     1
the yankees                                                                                                                1
green bay                                                                                                                  1
tottenham hotspur                                                                                                          1
oakland a's                                                                                                                1
atletico de madrid                                                                                                         1
chiefs                                                                                                                     1

In [16]:
# Replacing new york yankees ---------- CHECK WITH TEAM --- FOOTBALL
sports_v2['Q2'] = sports_v2['Q2'].replace(['yankees', 'ny yankees', 'the yankees', 'new york yankees football'], "new york yankees")

# Replacing los angeles lakers
sports_v2['Q2'] = sports_v2['Q2'].replace(['lakers', 'la lakers', 'laker', 'the lakers'], "los angeles lakers")

# Replacing green bay packers
sports_v2['Q2'] = sports_v2['Q2'].replace(['green bay', "packers"], "green bay packers")

# Replacing dallas cowboys
sports_v2['Q2'] = sports_v2['Q2'].replace(['cowboys'], "dallas cowboys")

# Replacing cleveland browns
sports_v2['Q2'] = sports_v2['Q2'].replace(['browns'], "cleveland browns")

# Replacing new england patriots
sports_v2['Q2'] = sports_v2['Q2'].replace(['patriots'], "new england patriots")

# Replacing new orleans saints
sports_v2['Q2'] = sports_v2['Q2'].replace(['saints if husband is watching', 'saints'], "new orleans saints")

# Replacing pittsburgh steelers
sports_v2['Q2'] = sports_v2['Q2'].replace(['steelers'], "pittsburgh steelers")

# Replacing philadelphia eagles
sports_v2['Q2'] = sports_v2['Q2'].replace(['eagles'], "philadelphia eagles")

# Replacing chicago bulls
sports_v2['Q2'] = sports_v2['Q2'].replace(['bulls', 'the bulls' ], "chicago bulls")

# Replacing boston red sox
sports_v2['Q2'] = sports_v2['Q2'].replace(['red sox ', 'redsox', 'red sox' ], "boston red sox")

# Replacing boston celtics
sports_v2['Q2'] = sports_v2['Q2'].replace(['celtics' ], "boston celtics")

# Replacing boston bruins
sports_v2['Q2'] = sports_v2['Q2'].replace(['bruins' ], "boston bruins")

# Replacing seattle seahawks
sports_v2['Q2'] = sports_v2['Q2'].replace(['seahawks' ], "seattle seahawks")

# Replacing philadelphia phillies
sports_v2['Q2'] = sports_v2['Q2'].replace(['philadelpia phillies', 'phillies' ], "philadelphia phillies")

# Replacing golden state warriors
sports_v2['Q2'] = sports_v2['Q2'].replace(['warriors' ], "golden state warriors")

# Replacing tampa bay buccaneers
sports_v2['Q2'] = sports_v2['Q2'].replace(['tampa bay bucaneers', 'tampa bucs' ], "tampa bay buccaneers")

# Replacing football
sports_v2['Q2'] = sports_v2['Q2'].replace(['foot ball' ], "football")

# Replacing cricket
sports_v2['Q2'] = sports_v2['Q2'].replace(['criket' ], "cricket")

# Replacing denver broncos
sports_v2['Q2'] = sports_v2['Q2'].replace(['broncos' ], "denver broncos")

# Replacing pittsburgh penguins
sports_v2['Q2'] = sports_v2['Q2'].replace(['pittsburgh pinguins' ], "pittsburgh penguins")

# Replacing new york knicks
sports_v2['Q2'] = sports_v2['Q2'].replace(['new york knicks hockey' ], "new york knicks")

# Replacing new york giants
sports_v2['Q2'] = sports_v2['Q2'].replace(['ny giants', 'giants', 'new york giants basketball' ], "new york giants")

# Replacing cleveland cavaliers
sports_v2['Q2'] = sports_v2['Q2'].replace(['cavs', 'cleveland cavs' ], "cleveland cavaliers")

# Replacing kansas city chiefs
sports_v2['Q2'] = sports_v2['Q2'].replace(['chiefs', 'kc chiefs' ], "kansas city chiefs")

# Replacing los angeles kings
sports_v2['Q2'] = sports_v2['Q2'].replace(['la kings' ], "los angeles kings")

# Replacing new york jets
sports_v2['Q2'] = sports_v2['Q2'].replace(['jets' ], "new york jets")

# Replacing baltimore ravens
sports_v2['Q2'] = sports_v2['Q2'].replace(['ravens' ], "baltimore ravens")

# Replacing washington nationals
sports_v2['Q2'] = sports_v2['Q2'].replace(['washington nats' ], "washington nationals")

# Replacing los angels dodgers
sports_v2['Q2'] = sports_v2['Q2'].replace(['dodgers' ], "los angels dodgers")

# Replacing atlanta falcons
sports_v2['Q2'] = sports_v2['Q2'].replace(['falcons' ], "atlanta falcons")

# Replacing las vegas raiders
sports_v2['Q2'] = sports_v2['Q2'].replace(['raiders' ], "las vegas raiders")

# Replacing st louis cardinals
sports_v2['Q2'] = sports_v2['Q2'].replace(['cardinals' ], "st louis cardinals")

# Replacing fc barcelona
sports_v2['Q2'] = sports_v2['Q2'].replace(['barcelona' ], "fc barcelona")

# Replacing houston astros
sports_v2['Q2'] = sports_v2['Q2'].replace(['astros' ], "houston astros")

# Replacing dallas mavericks
sports_v2['Q2'] = sports_v2['Q2'].replace(['mavericks' ], "dallas mavericks")

# Replacing dallas mavericks ---------- CHECK WITH TEAM
sports_v2['Q2'] = sports_v2['Q2'].replace(['rockets' ], "houston rockets")

# Replacing minnesota twins ---------- CHECK WITH TEAM
sports_v2['Q2'] = sports_v2['Q2'].replace(['twins' ], "minnesota twins")

# Replacing philadelphia flyers ---------- CHECK WITH TEAM
sports_v2['Q2'] = sports_v2['Q2'].replace(['flyers' ], "philadelphia flyers")

# updating teams
teams = sports_v2['Q2'][1:].unique()

In [17]:
# checking unique teams
sports_v2['Q2'][1:].nunique()

139

In [18]:
# all unique teams
sports_v2['Q2'][1:].value_counts(sort=True)
pd.set_option('max_rows', None)
sports_v2['Q2'][1:].value_counts(sort=True)

new york yankees                                                                                                          25
los angeles lakers                                                                                                        14
green bay packers                                                                                                         12
pittsburgh steelers                                                                                                       10
new england patriots                                                                                                       9
cleveland browns                                                                                                           8
dallas cowboys                                                                                                             8
chicago cubs                                                                                                               7
new orleans saints                                                                                                         7
kansas city chiefs                                                                                                         7
philadelphia eagles                                                                                                        7
seattle seahawks                                                                                                           7
none                                                                                                                       7
chicago bears                                                                                                              7
new york jets                                                                                                              5
baltimore ravens                                                                                                           5
dallas mavericks                                                                                                           5
golden state warriors                                                                                                      5
chicago bulls                                                                                                              5
new york giants                                                                                                            5
houston astros                                                                                                             5
atlanta braves                                                                                                             5
boston red sox                                                                                                             4
cricket                                                                                                                    4
las vegas raiders                                                                                                          4
miami heat                                                                                                                 4
st louis cardinals                                                                                                         4
philadelphia phillies                                                                                                      4
pittsburgh penguins                                                                                                        4
buffalo bills                                                                                                              4
manchester united                                                                                                          4
san francisco 49ers                                                                                                        4
football                                                                                                                   3
boston celtics                                                                                                             3
san antonio spurs                                                                                                          3
detroit lions                                                                                                              3
cleveland cavaliers                                                                                                        3
fc barcelona                                                                                                               3
tennessee titans                                                                                                           3
philadelphia flyers                                                                                                        2
st louis blues                                                                                                             2
washington nationals                                                                                                       2
texas rangers                                                                                                              2
houston texans                                                                                                             2
charlotte hornets                                                                                                          2
tennis                                                                                                                     2
los angels dodgers                                                                                                         2
chicago blackhawks                                                                                                         2
minnesota twins                                                                                                            2
colorado avalanche                                                                                                         2
phoenix suns                                                                                                               2
detroit red wings                                                                                                          2
washington wizards                                                                                                         2
tampa bay buccaneers                                                                                                       2
denver broncos                                                                                                             2
los angeles kings                                                                                                          2
houston rockets                                                                                                            2
new jersey devils                                                                                                          2
milwaukee bucks                                                                                                            2
new york mets                                                                                                              2
atlanta falcons                                                                                                            2
boston bruins                                                                                                              2
reds                                                                                                                       2
cleveland indians                                                                                                          2
basketball                                                                                                                 1
new york rangers                                                                                                           1
anaheim angels                                                                                                             1
wildcats                                                                                                                   1
unc tarheels men's basketball                                                                                              1
hendrick motor sports                                                                                                      1
mlb                                                                                                                        1
brooklyn nets                                                                                                              1
detroit tigers                                                                                                             1
columbus clippers                                                                                                          1
virginia tech hokies                                                                                                       1
samsung white                                                                                                              1
villanova wildcats                                                                                                         1
dallas stars                                                                                                               1
new york knicks                                                                                                            1
georgia bulldogs                                                                                                           1
austrlia                                                                                                                   1
chicago white sox                                                                                                          1
atlanta hawks                                                                                                              1
pittsburgh pirates                                                                                                         1
university of alabama                                                                                                      1
ndsu bison                                                                                                                 1
utah jazz                                                                                                                  1
columbus blue jackets                                                                                                      1
kentucky wildcats                                                                                                          1
start watching a few games pick out the one (or two) that appeals to you                                                   1
as team                                                                                                                    1
liverpool fc                                                                                                               1
colts                                                                                                                      1
michigan wolverines                                                                                                        1
softball                                                                                                                   1
juventus fc                                                                                                                1
oklahoma state cowboys                                                                                                     1
jacksonville jaguars                                                                                                       1
miami marlins                                                                                                              1
vegas golden knights                                                                                                       1
south carolina gamecocks                                                                                                   1
aggies                                                                                                                     1
arkansas razorbacks                                                                                                        1
edmonton oilers                                                                                                            1
fff                                                                                                                        1
boxing                                                                                                                     1
new york islanders                                                                                                         1
tennessee vols                                                                                                             1
nashville predators                                                                                                        1
tottenham hotspur                                                                                                          1
north carolina tar heels football                                                                                          1
purdue university basketball                                                                                               1
toronto maple leafs                                                                                                        1
nbl                                                                                                                        1
oakland a's                                                                                                                1
nba                                                                                                                        1
fc dallas                                                                                                                  1
badgers                                                                                                                    1
carolina panthers                                                                                                          1
cincinnati bengals                                                                                                         1
sport, team/player baseball, new york yankees football, new york giants basketball, new york knicks hockey, new jersey     1
ball                                                                                                                       1
capitals                                                                                                                   1
texas football                                                                                                             1
indiana pacers                                                                                                             1
nfl team                                                                                                                   1
florida state seminoles                                                                                                    1
atletico de madrid                                                                                                         1
chargers                                                                                                                   1
tampa bay rays                                                                                                             1
i don't watch sports                                                                                                       1
chelsea                                                                                                                    1
detroit pistons                                                                                                            1
padres                                                                                                                     1
miami hurricanes                                                                                                           1
brewers                                                                                                                    1
ou sooners                                                                                                                 1
dolfins                                                                                                                    1
montreal canadian hockey team                                                                                              1
Name: Q2, dtype: int64

In [19]:
sports_v2 = sports_v2.drop(0)

In [20]:
sports_v2['Q22'] = sports_v2['Q22'].astype('int')

In [21]:
conditions = [
    (sports_v2['Q22'] <= 25),
    (sports_v2['Q22'] >= 26) & (sports_v2['Q22'] <= 40),
    (sports_v2['Q22'] >= 41) & (sports_v2['Q22'] <= 55),
    (sports_v2['Q22'] >= 56) & (sports_v2['Q22'] <= 74),
    (sports_v2['Q22'] >= 75)
    ]

values = ['Gen Z', 'Millennial', 'Gen X', 'Boomer', 'Silent Gen']

sports_v2['generation'] = np.select(conditions, values)

In [22]:
sports_v2.iloc[:,0:3] = sports_v2.iloc[:,0:3].astype('int')
sports_v2.iloc[:,4:-1] = sports_v2.iloc[:,4:-1].astype('int')
sports_v2.dtypes

Progress                  int32
Duration (in seconds)     int32
Finished                  int32
Q2                       object
Q3_NPS_GROUP              int32
Q3                        int32
Q4_NPS_GROUP              int32
Q4                        int32
Q5_1                      int32
Q5_2                      int32
Q5_3                      int32
Q5_4                      int32
Q5_5                      int32
Q5_6                      int32
Q5_7                      int32
Q5_8                      int32
Q6_1                      int32
Q6_2                      int32
Q6_3                      int32
Q6_4                      int32
Q6_5                      int32
Q6_6                      int32
Q7_1                      int32
Q7_2                      int32
Q7_3                      int32
Q7_4                      int32
Q7_5                      int32
Q7_6                      int32
Q8                        int32
Q9_1                      int32
Q9_2                      int32
Q9_3                      int32
Q9_4                      int32
Q10_1                     int32
Q10_2                     int32
Q10_3                     int32
Q11_1                     int32
Q12_1                     int32
Q13_1                     int32
Q13_2                     int32
Q14_1                     int32
Q14_2                     int32
Q14_3                     int32
Q15_1                     int32
Q15_2                     int32
Q15_3                     int32
Q15_4                     int32
Q16_1                     int32
Q16_2                     int32
Q16_3                     int32
Q16_4                     int32
Q16_5                     int32
Q16_6                     int32
Q16_7                     int32
Q16_8                     int32
Q17_1                     int32
Q17_2                     int32
Q17_3                     int32
Q17_4                     int32
Q17_5                     int32
Q17_6                     int32
Q17_7                     int32
Q17_8                     int32
Q17_9                     int32
Q17_10                    int32
Q18_1                     int32
Q18_2                     int32
Q18_3                     int32
Q18_4                     int32
Q18_5                     int32
Q18_6                     int32
Q18_7                     int32
Q18_8                     int32
Q19_1                     int32
Q19_2                     int32
Q19_3                     int32
Q19_4                     int32
Q20_1                     int32
Q20_2                     int32
Q20_3                     int32
Q20_4                     int32
Q20_5                     int32
Q20_6                     int32
Q20_7                     int32
Q21_1                     int32
Q21_2                     int32
Q21_3                     int32
Q21_4                     int32
Q21_5                     int32
Q22                       int32
Q23                       int32
Q24                       int32
Q25                       int32
Q26_1                     int32
Q26_2                     int32
Q27                       int32
Q28#1_1                   int32
Q28#1_2                   int32
Q28#1_3                   int32
Q28#1_4                   int32
Q28#1_5                   int32
Q28#1_6                   int32
Q28#1_7                   int32
Q28#1_8                   int32
Q28#1_9                   int32
Q28#1_10                  int32
Q28#1_11                  int32
Q28#1_12                  int32
Q28#1_13                  int32
Q28#1_14                  int32
Q28#1_15                  int32
Q28#1_16                  int32
Q28#1_17                  int32
Q28#1_18                  int32
Q28#1_19                  int32
Q28#1_20                  int32
Q28#1_21                  int32
Q28#1_22                  int32
Q28#1_23                  int32
Q28#1_24                  int32
Q28#1_25                  int32
Q28#1_26                  int32
Q28#1_27                  int32
Q28#1_28                  int32
Q28#1_29                  int32
Q28#1_30                  int32
random                    int32
generation               object
dtype: object

In [23]:
# Define 'gender'
conditions1 = [
    (sports_v2['Q23'] == 1),
    (sports_v2['Q23'] == 2), 
    (sports_v2['Q22'] == 3),
    (sports_v2['Q23'] == 4)
    ]

values1 = ['Male', 'Female', 'Non-binary', 'Null']

sports_v2['gender'] = np.select(conditions1, values1)

In [24]:
# Define 'race'
conditions2 = [
    (sports_v2['Q24'] == 1),
    (sports_v2['Q24'] == 2), 
    (sports_v2['Q24'] == 3),
    (sports_v2['Q24'] == 4),
    (sports_v2['Q24'] == 5),
    (sports_v2['Q24'] == 6)
    ]

values2 = ['White', 'African American', 'Hispanic', 'Asian', 'Mixed Race', 'Other']

sports_v2['race'] = np.select(conditions2, values2)

In [25]:
# Define 'SES'
conditions3 = [
    (sports_v2['Q25'] == 1),
    (sports_v2['Q25'] == 2), 
    (sports_v2['Q25'] == 3),
    (sports_v2['Q25'] == 4)
    ]

values3 = ['<50k', '>50k & <100k', '>100k & <200k', '>200k']

sports_v2['SES'] = np.select(conditions3, values3)

In [26]:
# Define 'political_spectrum'
conditions4 = [
    (sports_v2['Q26_1'] == 1),
    (sports_v2['Q26_1'] == 2), 
    (sports_v2['Q26_1'] == 3),
    (sports_v2['Q26_1'] == 4),
    (sports_v2['Q26_1'] == 5),
    (sports_v2['Q26_1'] == 6),
    (sports_v2['Q26_1'] == 7)
    ]

values4 = ['Extremely Conservative', 'Moderately Conservative', 'Quite Conservative', 'Neutral', 'Quite Liberal', 'Moderately Conservative', 'Extremely Liberal']

sports_v2['political_spectrum'] = np.select(conditions4, values4)

In [27]:
# Define 'religious spectrum'
conditions5 = [
    (sports_v2['Q26_2'] == 1),
    (sports_v2['Q26_2'] == 2), 
    (sports_v2['Q26_2'] == 3),
    (sports_v2['Q26_2'] == 4),
    (sports_v2['Q26_2'] == 5),
    (sports_v2['Q26_2'] == 6),
    (sports_v2['Q26_2'] == 7)
    ]

values5 = ['Extremely Religious', 'Moderately Religious', 'Quite Religious', 'Neutral', 'Quite Non-religious', 'Usually Non-religious', 'Extremely Non-religious']

sports_v2['religious_spectrum'] = np.select(conditions5, values5)

In [28]:
# Define 'nationality'
conditions6 = [
    (sports_v2['Q27'] == 1),
    (sports_v2['Q27'] == 2), 
    (sports_v2['Q27'] == 3),
    (sports_v2['Q27'] == 4),
    (sports_v2['Q27'] == 5),
    (sports_v2['Q27'] == 6),
    (sports_v2['Q27'] == 7)
    ]

values6 = ['United States', 'Canada', 'Mexico', 'Latin America', 'Europe', 'Africa', 'Asia/Oceania']

sports_v2['nationality'] = np.select(conditions6, values6)

## Sports Fandom

In [29]:
sports_fandom = sports_v2.loc[:, ['Q2', 'Q3_NPS_GROUP', 'Q3', 'Q4_NPS_GROUP', 'Q4', 'Q5_1', 'Q5_2', 'Q5_3', 'Q5_4', 'Q5_5', 'Q5_6', 'Q5_7', 'Q5_8','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [30]:
sports_fandom.groupby(["generation", "gender"]).describe()

                  Q3_NPS_GROUP                                               \
                         count      mean       std  min  25%  50%  75%  max
generation gender
Boomer     Female         24.0  1.708333  0.806450  1.0  1.0  1.5  2.0  3.0
           Male           28.0  2.178571  0.772374  1.0  2.0  2.0  3.0  3.0
Gen X      0               1.0  1.000000       NaN  1.0  1.0  1.0  1.0  1.0
           Female         30.0  1.966667  0.889918  1.0  1.0  2.0  3.0  3.0
           Male           37.0  2.270270  0.769150  1.0  2.0  2.0  3.0  3.0
           Null            1.0  1.000000       NaN  1.0  1.0  1.0  1.0  1.0
Gen Z      Female         33.0  1.757576  0.751262  1.0  1.0  2.0  2.0  3.0
           Male           27.0  1.888889  0.800641  1.0  1.0  2.0  2.5  3.0
           Null            1.0  2.000000       NaN  2.0  2.0  2.0  2.0  2.0
Millennial Female         84.0  1.845238  0.768256  1.0  1.0  2.0  2.0  3.0
           Male           93.0  2.204301  0.801617  1.0  2.0  2.0  3.0  3.0
Silent Gen Female          1.0  3.000000       NaN  3.0  3.0  3.0  3.0  3.0
           Male            1.0  3.000000       NaN  3.0  3.0  3.0  3.0  3.0

                     Q3                                                      \
                  count       mean       std   min    25%   50%   75%   max
generation gender
Boomer     Female  24.0   6.291667  2.835783   0.0   4.75   6.5   8.0  10.0
           Male    28.0   7.321429  2.695038   0.0   7.00   8.0   9.0  10.0
Gen X      0        1.0   2.000000       NaN   2.0   2.00   2.0   2.0   2.0
           Female  30.0   6.333333  3.417332   0.0   3.25   7.5   9.0  10.0
           Male    37.0   7.567568  2.814057   0.0   7.00   8.0  10.0  10.0
           Null     1.0   3.000000       NaN   3.0   3.00   3.0   3.0   3.0
Gen Z      Female  33.0   6.121212  2.847780   0.0   4.00   7.0   8.0  10.0
           Male    27.0   7.074074  2.368478   2.0   5.50   8.0   8.5  10.0
           Null     1.0   8.000000       NaN   8.0   8.00   8.0   8.0   8.0
Millennial Female  84.0   6.607143  2.629847   0.0   5.00   7.0   8.0  10.0
           Male    93.0   7.494624  2.631844   0.0   7.00   8.0  10.0  10.0
Silent Gen Female   1.0  10.000000       NaN  10.0  10.00  10.0  10.0  10.0
           Male     1.0   9.000000       NaN   9.0   9.00   9.0   9.0   9.0

                  Q4_NPS_GROUP                                                \
                         count      mean       std  min  25%  50%   75%  max
generation gender
Boomer     Female         24.0  1.666667  0.868115  1.0  1.0  1.0  2.25  3.0
           Male           28.0  1.785714  0.832539  1.0  1.0  2.0  2.25  3.0
Gen X      0               1.0  1.000000       NaN  1.0  1.0  1.0  1.00  1.0
           Female         30.0  1.666667  0.844182  1.0  1.0  1.0  2.00  3.0
           Male           37.0  1.783784  0.750375  1.0  1.0  2.0  2.00  3.0
           Null            1.0  1.000000       NaN  1.0  1.0  1.0  1.00  1.0
Gen Z      Female         33.0  1.454545  0.753778  1.0  1.0  1.0  2.00  3.0
           Male           27.0  2.000000  0.832050  1.0  1.0  2.0  3.00  3.0
           Null            1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
Millennial Female         84.0  1.714286  0.800172  1.0  1.0  1.5  2.00  3.0
           Male           93.0  1.924731  0.837135  1.0  1.0  2.0  3.00  3.0
Silent Gen Female          1.0  3.000000       NaN  3.0  3.0  3.0  3.00  3.0
           Male            1.0  3.000000       NaN  3.0  3.0  3.0  3.00  3.0

                     Q4                                                       \
                  count       mean       std   min    25%   50%    75%   max
generation gender
Boomer     Female  24.0   6.083333  2.796219   0.0   5.00   6.0   8.25  10.0
           Male    28.0   6.142857  3.002644   0.0   4.00   7.0   8.25  10.0
Gen X      0        1.0   0.000000       NaN   0.0   0.00   0.0   0.00   0.0
           Female  30.0   5.166667  3.343376   0.0   2.00   5.5   8.00  10.0
           Male    37.0   6.000000  3.118048   0.0   5.00   7.0   8.00  10.0
           Null     1.0   1.000000       NaN   1.0   1.00   1.0   1.00   1.0
Gen Z      Female  33.0   5.151515  2.990832   0.0   3.00   6.0   7.00  10.0
           Male    27.0   6.925926  2.813784   0.0   5.50   8.0   9.00  10.0
           Null     1.0   8.000000       NaN   8.0   8.00   8.0   8.00   8.0
Millennial Female  84.0   5.976190  3.021913   0.0   3.75   6.5   8.00  10.0
           Male    93.0   6.752688  2.760970   0.0   5.00   7.0   9.00  10.0
Silent Gen Female   1.0  10.000000       NaN  10.0  10.00  10.0  10.00  10.0
           Male     1.0   9.000000       NaN   9.0   9.00   9.0   9.00   9.0

                   Q5_1                                                 Q5_2  \
                  count      mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  24.0  4.041667  2.136213  1.0  2.00  4.0  6.00  7.0  24.0
           Male    28.0  5.500000  1.621613  1.0  4.00  6.0  7.00  7.0  28.0
Gen X      0        1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
           Female  30.0  4.433333  2.254242  1.0  2.25  5.0  6.75  7.0  30.0
           Male    37.0  5.378378  1.737676  1.0  5.00  6.0  7.00  7.0  37.0
           Null     1.0  3.000000       NaN  3.0  3.00  3.0  3.00  3.0   1.0
Gen Z      Female  33.0  3.606061  2.207082  1.0  2.00  3.0  5.00  7.0  33.0
           Male    27.0  4.666667  2.166174  1.0  2.00  5.0  7.00  7.0  27.0
           Null     1.0  2.000000       NaN  2.0  2.00  2.0  2.00  2.0   1.0
Millennial Female  84.0  4.452381  2.267660  1.0  2.00  5.0  6.25  7.0  84.0
           Male    93.0  5.408602  1.825166  1.0  5.00  6.0  7.00  7.0  93.0
Silent Gen Female   1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
           Male     1.0  7.000000       NaN  7.0  7.00  7.0  7.00  7.0   1.0

                                                                Q5_3  \
                       mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  3.250000  1.594829  1.0  2.0  3.0  5.0  7.0  24.0
           Male    4.321429  1.743848  1.0  3.0  4.5  6.0  7.0  28.0
Gen X      0       3.000000       NaN  3.0  3.0  3.0  3.0  3.0   1.0
           Female  3.466667  2.270247  1.0  1.0  3.5  5.0  7.0  30.0
           Male    4.405405  1.992478  1.0  3.0  5.0  6.0  7.0  37.0
           Null    1.000000       NaN  1.0  1.0  1.0  1.0  1.0   1.0
Gen Z      Female  3.818182  2.113270  1.0  2.0  4.0  6.0  7.0  33.0
           Male    4.629630  2.221367  1.0  3.0  5.0  7.0  7.0  27.0
           Null    5.000000       NaN  5.0  5.0  5.0  5.0  5.0   1.0
Millennial Female  3.857143  2.217906  1.0  1.0  4.0  6.0  7.0  84.0
           Male    4.494624  2.019598  1.0  3.0  5.0  6.0  7.0  93.0
Silent Gen Female  6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0
           Male    4.000000       NaN  4.0  4.0  4.0  4.0  4.0   1.0

                                                                Q5_4  \
                       mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  4.500000  2.021622  1.0  3.0  5.0  6.0  7.0  24.0
           Male    4.500000  2.185813  1.0  2.0  4.5  7.0  7.0  28.0
Gen X      0       3.000000       NaN  3.0  3.0  3.0  3.0  3.0   1.0
           Female  3.400000  2.206573  1.0  1.0  3.5  5.0  7.0  30.0
           Male    4.297297  2.106404  1.0  3.0  5.0  6.0  7.0  37.0
           Null    2.000000       NaN  2.0  2.0  2.0  2.0  2.0   1.0
Gen Z      Female  3.515152  1.970425  1.0  2.0  4.0  5.0  7.0  33.0
           Male    2.555556  1.783112  1.0  1.0  2.0  3.5  7.0  27.0
           Null    2.000000       NaN  2.0  2.0  2.0  2.0  2.0   1.0
Millennial Female  3.523810  2.102644  1.0  1.0  4.0  5.0  7.0  84.0
           Male    4.387097  2.016412  1.0  3.0  5.0  6.0  7.0  93.0
Silent Gen Female  7.000000       NaN  7.0  7.0  7.0  7.0  7.0   1.0
           Male    6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0

                                                                Q5_5  \
                       mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  2.041667  1.267629  1.0  1.0  1.5  3.0  5.0  24.0
           Male    3.785714  2.200289  1.0  2.0  4.0  5.0  7.0  28.0
Gen X      0       1.000000       NaN  1.0  1.0  1.0  1.0  1.0   1.0
           Female  3.200000  1.882771  1.0  1.0  3.5  5.0  7.0  30.0
           Male    3.891892  1.983036  1.0  2.0  4.0  6.0  7.0  37.0
           Null    1.000000       NaN  1.0  1.0  1.0  1.0  1.0   1.0
Gen Z      Female  3.030303  1.911885  1.0  1.0  3.0  5.0  7.0  33.0
           Male    2.851852  1.994294  1.0  1.0  2.0  4.5  7.0  27.0
           Null    2.000000       NaN  2.0  2.0  2.0  2.0  2.0   1.0
Millennial Female  2.869048  2.063917  1.0  1.0  2.0  4.0  7.0  84.0
           Male    3.559140  1.980680  1.0  2.0  4.0  5.0  7.0  93.0
Silent Gen Female  3.000000       NaN  3.0  3.0  3.0  3.0  3.0   1.0
           Male    4.000000       NaN  4.0  4.0  4.0  4.0  4.0   1.0

                                                                 Q5_6  \
                       mean       std  min  25%  50%   75%  max count
generation gender
Boomer     Female  2.375000  1.689160  1.0  1.0  2.0  3.25  7.0  24.0
           Male    3.000000  1.885618  1.0  1.0  2.5  4.00  6.0  28.0
Gen X      0       1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
           Female  2.533333  2.046584  1.0  1.0  1.5  3.75  7.0  30.0
           Male    3.405405  2.061006  1.0  2.0  3.0  5.00  7.0  37.0
           Null    1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
Gen Z      Female  3.030303  1.758637  1.0  1.0  3.0  4.00  6.0  33.0
           Male    2.962963  1.890899  1.0  2.0  2.0  4.00  7.0  27.0
           Null    7.000000       NaN  7.0  7.0  7.0  7.00  7.0   1.0
Millennial Female  2.630952  1.861336  1.0  1.0  2.0  4.00  7.0  84.0
           Male    3.118280  1.960753  1.0  1.0  3.0  5.00  7.0  93.0
Silent Gen Female  1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
           Male    2.000000       NaN  2.0  2.0  2.0  2.00  2.0   1.0

                                                                 Q5_7  \
                       mean       std  min  25%  50%   75%  max count
generation gender
Boomer     Female  1.416667  0.829702  1.0  1.0  1.0  1.25  4.0  24.0
           Male    2.285714  1.843048  1.0  1.0  1.0  4.00  6.0  28.0
Gen X      0       1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
           Female  2.433333  1.941974  1.0  1.0  1.0  4.00  7.0  30.0
           Male    2.729730  2.063555  1.0  1.0  2.0  5.00  6.0  37.0
           Null    1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
Gen Z      Female  3.424242  2.424231  1.0  1.0  4.0  6.00  7.0  33.0
           Male    3.481481  2.242429  1.0  1.5  3.0  6.00  7.0  27.0
           Null    6.000000       NaN  6.0  6.0  6.0  6.00  6.0   1.0
Millennial Female  2.095238  1.767300  1.0  1.0  1.0  2.25  7.0  84.0
           Male    3.258065  2.125943  1.0  1.0  3.0  5.00  7.0  93.0
Silent Gen Female  1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
           Male    2.000000       NaN  2.0  2.0  2.0  2.00  2.0   1.0

                                                                  Q5_8  \
                       mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  2.208333  1.841058  1.0  1.00  1.0  2.25  7.0  24.0
           Male    3.178571  1.722478  1.0  1.75  4.0  5.00  6.0  28.0
Gen X      0       1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
           Female  2.433333  2.011747  1.0  1.00  1.0  3.75  7.0  30.0
           Male    3.162162  1.993232  1.0  1.00  3.0  5.00  7.0  37.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
Gen Z      Female  3.090909  2.021195  1.0  1.00  3.0  5.00  7.0  33.0
           Male    2.703704  1.612805  1.0  1.00  2.0  4.00  6.0  27.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
Millennial Female  2.083333  1.607275  1.0  1.00  1.0  3.00  7.0  84.0
           Male    3.182796  1.829387  1.0  1.00  3.0  4.00  7.0  93.0
Silent Gen Female  1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
           Male    2.000000       NaN  2.0  2.00  2.0  2.00  2.0   1.0


                       mean       std  min   25%  50%   75%  max
generation gender
Boomer     Female  3.291667  1.966661  1.0  1.00  4.0  4.25  7.0
           Male    3.892857  1.872595  1.0  2.75  4.0  5.00  7.0
Gen X      0       4.000000       NaN  4.0  4.00  4.0  4.00  4.0
           Female  3.433333  2.192201  1.0  1.00  3.5  5.00  7.0
           Male    3.918919  2.032765  1.0  2.00  4.0  5.00  7.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0
Gen Z      Female  3.090909  1.909902  1.0  1.00  3.0  5.00  7.0
           Male    4.000000  2.000000  1.0  2.00  4.0  6.00  7.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0
Millennial Female  2.785714  1.976192  1.0  1.00  2.0  4.00  7.0
           Male    3.752688  1.920461  1.0  2.00  4.0  5.00  7.0
Silent Gen Female  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
           Male    2.000000       NaN  2.0  2.00  2.0  2.00  2.0

## Sports Fans

In [31]:
sports_fans = sports_v2.loc[:, ['Q17_1', 'Q17_2', 'Q17_3', 'Q17_4','Q17_5','Q17_6','Q17_7','Q17_8','Q17_9','Q17_10','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [32]:
sports_fans.groupby(["generation", "gender"]).describe()

                  Q17_1                                              Q17_2  \
                  count      mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  24.0  5.791667  1.693444  1.0  5.0  7.0  7.0  7.0  24.0
           Male    28.0  5.714286  1.150109  3.0  5.0  6.0  7.0  7.0  28.0
Gen X      0        1.0  7.000000       NaN  7.0  7.0  7.0  7.0  7.0   1.0
           Female  30.0  5.600000  1.404426  1.0  5.0  6.0  7.0  7.0  30.0
           Male    37.0  5.432432  1.405160  1.0  5.0  6.0  6.0  7.0  37.0
           Null     1.0  1.000000       NaN  1.0  1.0  1.0  1.0  1.0   1.0
Gen Z      Female  33.0  5.636364  1.294657  3.0  5.0  5.0  7.0  7.0  33.0
           Male    27.0  5.370370  1.713030  2.0  4.0  6.0  7.0  7.0  27.0
           Null     1.0  5.000000       NaN  5.0  5.0  5.0  5.0  5.0   1.0
Millennial Female  84.0  5.690476  1.649945  1.0  5.0  6.0  7.0  7.0  84.0
           Male    93.0  5.612903  1.560604  1.0  5.0  6.0  7.0  7.0  93.0
Silent Gen Female   1.0  7.000000       NaN  7.0  7.0  7.0  7.0  7.0   1.0
           Male     1.0  6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0

                                                                Q17_3  \
                       mean       std  min  25%  50%   75%  max count
generation gender
Boomer     Female  5.500000  1.587998  2.0  4.0  6.0  7.00  7.0  24.0
           Male    5.428571  1.451144  2.0  5.0  6.0  6.25  7.0  28.0
Gen X      0       7.000000       NaN  7.0  7.0  7.0  7.00  7.0   1.0
           Female  5.500000  1.502871  1.0  5.0  6.0  7.00  7.0  30.0
           Male    5.081081  1.516179  2.0  4.0  5.0  6.00  7.0  37.0
           Null    2.000000       NaN  2.0  2.0  2.0  2.00  2.0   1.0
Gen Z      Female  6.030303  0.983770  4.0  5.0  6.0  7.00  7.0  33.0
           Male    5.370370  1.418237  3.0  4.0  6.0  7.00  7.0  27.0
           Null    5.000000       NaN  5.0  5.0  5.0  5.00  5.0   1.0
Millennial Female  5.523810  1.689630  1.0  5.0  6.0  7.00  7.0  84.0
           Male    5.344086  1.455833  1.0  4.0  6.0  7.00  7.0  93.0
Silent Gen Female  5.000000       NaN  5.0  5.0  5.0  5.00  5.0   1.0
           Male    5.000000       NaN  5.0  5.0  5.0  5.00  5.0   1.0

                                                                 Q17_4  \
                       mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  5.041667  1.876147  1.0  3.75  5.5  7.00  7.0  24.0
           Male    4.464286  1.598197  1.0  3.75  5.0  5.25  7.0  28.0
Gen X      0       7.000000       NaN  7.0  7.00  7.0  7.00  7.0   1.0
           Female  4.600000  1.610312  1.0  4.00  5.0  5.75  7.0  30.0
           Male    3.945946  1.971265  1.0  2.00  4.0  6.00  7.0  37.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
Gen Z      Female  4.606061  1.801725  1.0  4.00  5.0  6.00  7.0  33.0
           Male    4.074074  1.685365  2.0  3.00  4.0  5.50  7.0  27.0
           Null    5.000000       NaN  5.0  5.00  5.0  5.00  5.0   1.0
Millennial Female  4.511905  2.014968  1.0  3.00  5.0  6.00  7.0  84.0
           Male    4.290323  1.833153  1.0  3.00  4.0  6.00  7.0  93.0
Silent Gen Female  6.000000       NaN  6.0  6.00  6.0  6.00  6.0   1.0
           Male    5.000000       NaN  5.0  5.00  5.0  5.00  5.0   1.0

                                                               Q17_5  \
                       mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  5.750000  1.452135  3.0  4.0  6.0  7.0  7.0  24.0
           Male    5.285714  1.696557  2.0  5.0  6.0  7.0  7.0  28.0
Gen X      0       4.000000       NaN  4.0  4.0  4.0  4.0  4.0   1.0
           Female  5.200000  1.562491  1.0  5.0  5.0  6.0  7.0  30.0
           Male    5.054054  1.432673  2.0  4.0  5.0  6.0  7.0  37.0
           Null    1.000000       NaN  1.0  1.0  1.0  1.0  1.0   1.0
Gen Z      Female  5.303030  1.629510  1.0  4.0  6.0  7.0  7.0  33.0
           Male    5.148148  1.586086  2.0  4.0  5.0  6.5  7.0  27.0
           Null    6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0
Millennial Female  5.000000  1.938823  1.0  4.0  5.5  7.0  7.0  84.0
           Male    4.924731  1.695496  1.0  4.0  5.0  6.0  7.0  93.0
Silent Gen Female  7.000000       NaN  7.0  7.0  7.0  7.0  7.0   1.0
           Male    6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0

                                                                 Q17_6  \
                       mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  4.833333  1.736229  1.0  3.75  5.0  6.25  7.0  24.0
           Male    4.928571  1.698116  1.0  4.00  5.0  6.00  7.0  28.0
Gen X      0       6.000000       NaN  6.0  6.00  6.0  6.00  6.0   1.0
           Female  3.933333  1.910648  1.0  2.00  4.0  5.00  7.0  30.0
           Male    4.567568  1.878837  1.0  3.00  5.0  6.00  7.0  37.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
Gen Z      Female  4.303030  1.740777  1.0  3.00  4.0  5.00  7.0  33.0
           Male    4.111111  1.804553  1.0  2.50  4.0  5.00  7.0  27.0
           Null    4.000000       NaN  4.0  4.00  4.0  4.00  4.0   1.0
Millennial Female  4.440476  2.055561  1.0  3.00  5.0  6.00  7.0  84.0
           Male    4.838710  1.643765  1.0  4.00  5.0  6.00  7.0  93.0
Silent Gen Female  7.000000       NaN  7.0  7.00  7.0  7.00  7.0   1.0
           Male    5.000000       NaN  5.0  5.00  5.0  5.00  5.0   1.0

                                                                Q17_7  \
                       mean       std  min  25%  50%   75%  max count
generation gender
Boomer     Female  1.875000  1.454005  1.0  1.0  1.0  2.25  5.0  24.0
           Male    2.571429  1.989390  1.0  1.0  2.0  4.00  7.0  28.0
Gen X      0       1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
           Female  2.500000  1.925330  1.0  1.0  1.0  4.00  6.0  30.0
           Male    3.081081  2.165107  1.0  1.0  2.0  5.00  7.0  37.0
           Null    1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0
Gen Z      Female  4.272727  1.988604  1.0  3.0  5.0  6.00  7.0  33.0
           Male    4.148148  1.994294  1.0  3.0  4.0  6.00  7.0  27.0
           Null    3.000000       NaN  3.0  3.0  3.0  3.00  3.0   1.0
Millennial Female  3.357143  2.003869  1.0  1.0  3.0  5.00  7.0  84.0
           Male    3.172043  2.268037  1.0  1.0  2.0  5.00  7.0  93.0
Silent Gen Female  4.000000       NaN  4.0  4.0  4.0  4.00  4.0   1.0
           Male    1.000000       NaN  1.0  1.0  1.0  1.00  1.0   1.0

                                                                 Q17_8  \
                       mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  2.458333  1.382473  1.0  1.00  2.0  3.25  5.0  24.0
           Male    2.535714  1.794686  1.0  1.00  2.0  4.00  7.0  28.0
Gen X      0       1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
           Female  3.100000  1.787890  1.0  1.25  3.0  4.75  6.0  30.0
           Male    2.972973  1.878038  1.0  1.00  3.0  5.00  6.0  37.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
Gen Z      Female  3.727273  1.956922  1.0  2.00  3.0  5.00  7.0  33.0
           Male    3.000000  2.201398  1.0  1.00  2.0  4.50  7.0  27.0
           Null    3.000000       NaN  3.0  3.00  3.0  3.00  3.0   1.0
Millennial Female  3.571429  2.037514  1.0  2.00  3.5  5.00  7.0  84.0
           Male    3.053763  2.001986  1.0  1.00  2.0  5.00  7.0  93.0
Silent Gen Female  5.000000       NaN  5.0  5.00  5.0  5.00  5.0   1.0
           Male    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0

                                                                 Q17_9  \
                       mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  3.291667  1.944427  1.0  2.00  3.0  4.25  7.0  24.0
           Male    3.821429  1.925532  1.0  2.00  4.0  5.00  7.0  28.0
Gen X      0       3.000000       NaN  3.0  3.00  3.0  3.00  3.0   1.0
           Female  4.200000  1.827001  1.0  2.25  5.0  5.00  7.0  30.0
           Male    3.756757  1.949436  1.0  2.00  4.0  5.00  7.0  37.0
           Null    2.000000       NaN  2.0  2.00  2.0  2.00  2.0   1.0
Gen Z      Female  3.848485  2.017443  1.0  2.00  3.0  5.00  7.0  33.0
           Male    4.148148  1.915598  1.0  2.50  5.0  6.00  7.0  27.0
           Null    3.000000       NaN  3.0  3.00  3.0  3.00  3.0   1.0
Millennial Female  4.095238  2.033568  1.0  2.75  4.0  6.00  7.0  84.0
           Male    4.301075  1.875384  1.0  3.00  5.0  6.00  7.0  93.0
Silent Gen Female  2.000000       NaN  2.0  2.00  2.0  2.00  2.0   1.0
           Male    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0

                                                                Q17_10  \
                       mean       std  min  25%  50%   75%  max  count
generation gender
Boomer     Female  2.416667  1.691839  1.0  1.0  2.0  4.00  7.0   24.0
           Male    2.571429  1.874361  1.0  1.0  2.0  4.00  7.0   28.0
Gen X      0       7.000000       NaN  7.0  7.0  7.0  7.00  7.0    1.0
           Female  2.466667  1.756433  1.0  1.0  2.0  4.00  6.0   30.0
           Male    2.972973  1.992855  1.0  1.0  2.0  5.00  6.0   37.0
           Null    1.000000       NaN  1.0  1.0  1.0  1.00  1.0    1.0
Gen Z      Female  3.060606  2.105638  1.0  1.0  3.0  5.00  7.0   33.0
           Male    2.629630  1.964065  1.0  1.0  2.0  4.00  7.0   27.0
           Null    3.000000       NaN  3.0  3.0  3.0  3.00  3.0    1.0
Millennial Female  2.547619  1.832799  1.0  1.0  2.0  3.25  7.0   84.0
           Male    3.279570  2.066112  1.0  1.0  3.0  5.00  7.0   93.0
Silent Gen Female  1.000000       NaN  1.0  1.0  1.0  1.00  1.0    1.0
           Male    2.000000       NaN  2.0  2.0  2.0  2.00  2.0    1.0


                       mean       std  min   25%  50%   75%  max
generation gender
Boomer     Female  3.041667  1.601064  1.0  1.75  3.0  4.00  6.0
           Male    3.714286  1.959916  1.0  2.00  4.0  5.25  7.0
Gen X      0       1.000000       NaN  1.0  1.00  1.0  1.00  1.0
           Female  3.233333  2.095699  1.0  1.00  3.5  5.00  7.0
           Male    3.918919  2.046384  1.0  3.00  4.0  6.00  7.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0
Gen Z      Female  3.121212  2.204506  1.0  1.00  3.0  5.00  7.0
           Male    3.481481  1.908894  1.0  2.00  4.0  5.00  7.0
           Null    3.000000       NaN  3.0  3.00  3.0  3.00  3.0
Millennial Female  3.035714  1.947791  1.0  1.00  3.0  5.00  7.0
           Male    3.548387  1.856341  1.0  2.00  4.0  5.00  7.0
Silent Gen Female  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
           Male    5.000000       NaN  5.0  5.00  5.0  5.00  5.0

In [44]:
# Q17_1: a fan of following? - Movies
sports_fans.groupby(['generation', 'gender'])['Q17_1'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (4.0, 7.0]                   0.791667
                    (0.993, 4.0]                 0.208333
            Male    (5.0, 7.0]                   0.642857
                    (2.995, 5.0]                 0.357143
Gen X       0       (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Female  (4.0, 7.0]                   0.833333
                    (0.993, 4.0]                 0.166667
            Male    (4.0, 7.0]                   0.837838
                    (0.993, 4.0]                 0.162162
            Null    (0.998, 1.0]                 1.000000
                    (1.0, 1.001]                 0.000000
Gen Z       Female  (2.995, 5.0]                 0.515152
                    (5.0, 7.0]                   0.484848
            Male    (4.5, 7.0]                   0.666667
                    (1.9940000000000002, 4.5]    0.333333
            Null    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Millennial  Female  (4.0, 7.0]                   0.845238
                    (0.993, 4.0]                 0.154762
            Male    (4.0, 7.0]                   0.784946
                    (0.993, 4.0]                 0.215054
Silent Gen  Female  (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Male    (5.992999999999999, 6.0]     1.000000
                    (6.0, 6.006]                 0.000000
Name: Q17_1, dtype: float64

In [35]:
# Q17_2: a fan of following? - TV shows
sports_fans.groupby(['generation', 'gender'])['Q17_2'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (4.5, 7.0]                   0.708333
                    (1.9940000000000002, 4.5]    0.291667
            Male    (4.5, 7.0]                   0.785714
                    (1.9940000000000002, 4.5]    0.214286
Gen X       0       (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Female  (4.0, 7.0]                   0.800000
                    (0.993, 4.0]                 0.200000
            Male    (4.5, 7.0]                   0.675676
                    (1.9940000000000002, 4.5]    0.324324
            Null    (1.997, 2.0]                 1.000000
                    (2.0, 2.002]                 0.000000
Gen Z       Female  (5.5, 7.0]                   0.666667
                    (3.996, 5.5]                 0.333333
            Male    (5.0, 7.0]                   0.518519
                    (2.995, 5.0]                 0.481481
            Null    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Millennial  Female  (4.0, 7.0]                   0.761905
                    (0.993, 4.0]                 0.238095
            Male    (4.0, 7.0]                   0.688172
                    (0.993, 4.0]                 0.311828
Silent Gen  Female  (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
            Male    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Name: Q17_2, dtype: float64

In [36]:
# Q17_3: a fan of following? - Actors
sports_fans.groupby(['generation', 'gender'])['Q17_3'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (4.0, 7.0]                   0.583333
                    (0.993, 4.0]                 0.416667
            Male    (4.0, 7.0]                   0.535714
                    (0.993, 4.0]                 0.464286
Gen X       0       (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Female  (4.0, 7.0]                   0.600000
                    (0.993, 4.0]                 0.400000
            Male    (0.993, 4.0]                 0.621622
                    (4.0, 7.0]                   0.378378
            Null    (0.998, 1.0]                 1.000000
                    (1.0, 1.001]                 0.000000
Gen Z       Female  (4.0, 7.0]                   0.606061
                    (0.993, 4.0]                 0.393939
            Male    (1.9940000000000002, 4.5]    0.629630
                    (4.5, 7.0]                   0.370370
            Null    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Millennial  Female  (4.0, 7.0]                   0.547619
                    (0.993, 4.0]                 0.452381
            Male    (0.993, 4.0]                 0.559140
                    (4.0, 7.0]                   0.440860
Silent Gen  Female  (5.992999999999999, 6.0]     1.000000
                    (6.0, 6.006]                 0.000000
            Male    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Name: Q17_3, dtype: float64

In [37]:
# Q17_4: a fan of following? - Musicians
sports_fans.groupby(['generation', 'gender'])['Q17_4'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (5.0, 7.0]                   0.666667
                    (2.995, 5.0]                 0.333333
            Male    (4.5, 7.0]                   0.785714
                    (1.9940000000000002, 4.5]    0.214286
Gen X       0       (3.995, 4.0]                 1.000000
                    (4.0, 4.004]                 0.000000
            Female  (4.0, 7.0]                   0.800000
                    (0.993, 4.0]                 0.200000
            Male    (4.5, 7.0]                   0.702703
                    (1.9940000000000002, 4.5]    0.297297
            Null    (0.998, 1.0]                 1.000000
                    (1.0, 1.001]                 0.000000
Gen Z       Female  (4.0, 7.0]                   0.696970
                    (0.993, 4.0]                 0.303030
            Male    (4.5, 7.0]                   0.666667
                    (1.9940000000000002, 4.5]    0.333333
            Null    (5.992999999999999, 6.0]     1.000000
                    (6.0, 6.006]                 0.000000
Millennial  Female  (4.0, 7.0]                   0.654762
                    (0.993, 4.0]                 0.345238
            Male    (4.0, 7.0]                   0.645161
                    (0.993, 4.0]                 0.354839
Silent Gen  Female  (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Male    (5.992999999999999, 6.0]     1.000000
                    (6.0, 6.006]                 0.000000
Name: Q17_4, dtype: float64

In [38]:
# Q17_5: a fan of following? - Comedians
sports_fans.groupby(['generation', 'gender'])['Q17_5'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (4.0, 7.0]                  0.625000
                    (0.993, 4.0]                0.375000
            Male    (4.0, 7.0]                  0.571429
                    (0.993, 4.0]                0.428571
Gen X       0       (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
            Female  (0.993, 4.0]                0.533333
                    (4.0, 7.0]                  0.466667
            Male    (4.0, 7.0]                  0.621622
                    (0.993, 4.0]                0.378378
            Null    (0.998, 1.0]                1.000000
                    (1.0, 1.001]                0.000000
Gen Z       Female  (0.993, 4.0]                0.545455
                    (4.0, 7.0]                  0.454545
            Male    (0.993, 4.0]                0.592593
                    (4.0, 7.0]                  0.407407
            Null    (3.995, 4.0]                1.000000
                    (4.0, 4.004]                0.000000
Millennial  Female  (4.0, 7.0]                  0.547619
                    (0.993, 4.0]                0.452381
            Male    (4.0, 7.0]                  0.569892
                    (0.993, 4.0]                0.430108
Silent Gen  Female  (6.992, 7.0]                1.000000
                    (7.0, 7.007]                0.000000
            Male    (4.994, 5.0]                1.000000
                    (5.0, 5.005]                0.000000
Name: Q17_5, dtype: float64

In [39]:
# Q17_6: a fan of following? - Social media based personalities such as streamers or influencers
sports_fans.groupby(['generation', 'gender'])['Q17_6'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.995, 3.0]    0.833333
                    (3.0, 5.0]      0.166667
            Male    (0.993, 4.0]    0.785714
                    (4.0, 7.0]      0.214286
Gen X       0       (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
            Female  (0.994, 3.5]    0.666667
                    (3.5, 6.0]      0.333333
            Male    (0.993, 4.0]    0.648649
                    (4.0, 7.0]      0.351351
            Null    (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
Gen Z       Female  (4.0, 7.0]      0.515152
                    (0.993, 4.0]    0.484848
            Male    (0.993, 4.0]    0.555556
                    (4.0, 7.0]      0.444444
            Null    (2.996, 3.0]    1.000000
                    (3.0, 3.003]    0.000000
Millennial  Female  (0.993, 4.0]    0.702381
                    (4.0, 7.0]      0.297619
            Male    (0.993, 4.0]    0.677419
                    (4.0, 7.0]      0.322581
Silent Gen  Female  (3.995, 4.0]    1.000000
                    (4.0, 4.004]    0.000000
            Male    (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
Name: Q17_6, dtype: float64

In [40]:
# Q17_7: a fan of following? - Fashion brands
sports_fans.groupby(['generation', 'gender'])['Q17_7'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.995, 3.0]    0.750000
                    (3.0, 5.0]      0.250000
            Male    (0.993, 4.0]    0.821429
                    (4.0, 7.0]      0.178571
Gen X       0       (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
            Female  (0.994, 3.5]    0.600000
                    (3.5, 6.0]      0.400000
            Male    (0.994, 3.5]    0.594595
                    (3.5, 6.0]      0.405405
            Null    (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
Gen Z       Female  (0.993, 4.0]    0.636364
                    (4.0, 7.0]      0.363636
            Male    (0.993, 4.0]    0.740741
                    (4.0, 7.0]      0.259259
            Null    (2.996, 3.0]    1.000000
                    (3.0, 3.003]    0.000000
Millennial  Female  (0.993, 4.0]    0.690476
                    (4.0, 7.0]      0.309524
            Male    (0.993, 4.0]    0.720430
                    (4.0, 7.0]      0.279570
Silent Gen  Female  (4.994, 5.0]    1.000000
                    (5.0, 5.005]    0.000000
            Male    (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
Name: Q17_7, dtype: float64

In [41]:
# Q17_8: a fan of following? - Products (Coca-Cola, Apple, etc.)
sports_fans.groupby(['generation', 'gender'])['Q17_8'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.993, 4.0]    0.750000
                    (4.0, 7.0]      0.250000
            Male    (0.993, 4.0]    0.607143
                    (4.0, 7.0]      0.392857
Gen X       0       (2.996, 3.0]    1.000000
                    (3.0, 3.003]    0.000000
            Female  (4.0, 7.0]      0.566667
                    (0.993, 4.0]    0.433333
            Male    (0.993, 4.0]    0.594595
                    (4.0, 7.0]      0.405405
            Null    (1.997, 2.0]    1.000000
                    (2.0, 2.002]    0.000000
Gen Z       Female  (0.993, 4.0]    0.606061
                    (4.0, 7.0]      0.393939
            Male    (4.0, 7.0]      0.555556
                    (0.993, 4.0]    0.444444
            Null    (2.996, 3.0]    1.000000
                    (3.0, 3.003]    0.000000
Millennial  Female  (0.993, 4.0]    0.583333
                    (4.0, 7.0]      0.416667
            Male    (4.0, 7.0]      0.516129
                    (0.993, 4.0]    0.483871
Silent Gen  Female  (1.997, 2.0]    1.000000
                    (2.0, 2.002]    0.000000
            Male    (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
Name: Q17_8, dtype: float64

In [42]:
# Q17_9: a fan of following? - Politicians
sports_fans.groupby(['generation', 'gender'])['Q17_9'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.993, 4.0]    0.916667
                    (4.0, 7.0]      0.083333
            Male    (0.993, 4.0]    0.821429
                    (4.0, 7.0]      0.178571
Gen X       0       (6.992, 7.0]    1.000000
                    (7.0, 7.007]    0.000000
            Female  (0.994, 3.5]    0.700000
                    (3.5, 6.0]      0.300000
            Male    (0.994, 3.5]    0.621622
                    (3.5, 6.0]      0.378378
            Null    (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
Gen Z       Female  (0.993, 4.0]    0.727273
                    (4.0, 7.0]      0.272727
            Male    (0.993, 4.0]    0.777778
                    (4.0, 7.0]      0.222222
            Null    (2.996, 3.0]    1.000000
                    (3.0, 3.003]    0.000000
Millennial  Female  (0.993, 4.0]    0.821429
                    (4.0, 7.0]      0.178571
            Male    (0.993, 4.0]    0.688172
                    (4.0, 7.0]      0.311828
Silent Gen  Female  (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
            Male    (1.997, 2.0]    1.000000
                    (2.0, 2.002]    0.000000
Name: Q17_9, dtype: float64

In [43]:
# Q17_10:a fan of following? - Universities
sports_fans.groupby(['generation', 'gender'])['Q17_10'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.994, 3.5]    0.583333
                    (3.5, 6.0]      0.416667
            Male    (0.993, 4.0]    0.642857
                    (4.0, 7.0]      0.357143
Gen X       0       (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
            Female  (0.993, 4.0]    0.666667
                    (4.0, 7.0]      0.333333
            Male    (0.993, 4.0]    0.594595
                    (4.0, 7.0]      0.405405
            Null    (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
Gen Z       Female  (0.993, 4.0]    0.727273
                    (4.0, 7.0]      0.272727
            Male    (0.993, 4.0]    0.666667
                    (4.0, 7.0]      0.333333
            Null    (2.996, 3.0]    1.000000
                    (3.0, 3.003]    0.000000
Millennial  Female  (0.993, 4.0]    0.726190
                    (4.0, 7.0]      0.273810
            Male    (0.993, 4.0]    0.709677
                    (4.0, 7.0]      0.290323
Silent Gen  Female  (0.998, 1.0]    1.000000
                    (1.0, 1.001]    0.000000
            Male    (4.994, 5.0]    1.000000
                    (5.0, 5.005]    0.000000
Name: Q17_10, dtype: float64

## Sports Fan Demographics

In [45]:
sports_fan_demographics = sports_v2.loc[:, ['Q18_1','Q18_2','Q18_3','Q18_4','Q18_5','Q18_6','Q18_7','Q18_8','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [46]:
sports_fan_demographics.groupby(["generation", "gender"]).describe()

                  Q18_1                                                Q18_2  \
                  count      mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  24.0  4.041667  2.095112  1.0  2.75  4.0  5.25  7.0  24.0
           Male    28.0  4.571429  1.596955  1.0  4.00  5.0  6.00  7.0  28.0
Gen X      0        1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
           Female  30.0  3.900000  1.988762  1.0  2.00  4.0  5.00  7.0  30.0
           Male    37.0  4.540541  1.952130  1.0  3.00  5.0  6.00  7.0  37.0
           Null     1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
Gen Z      Female  33.0  4.606061  1.748917  1.0  4.00  5.0  6.00  7.0  33.0
           Male    27.0  4.814815  1.819489  1.0  4.00  5.0  6.00  7.0  27.0
           Null     1.0  4.000000       NaN  4.0  4.00  4.0  4.00  4.0   1.0
Millennial Female  84.0  4.404762  1.927099  1.0  2.00  5.0  6.00  7.0  84.0
           Male    93.0  4.537634  1.703954  1.0  4.00  5.0  6.00  7.0  93.0
Silent Gen Female   1.0  6.000000       NaN  6.0  6.00  6.0  6.00  6.0   1.0
           Male     1.0  6.000000       NaN  6.0  6.00  6.0  6.00  6.0   1.0

                                                                 Q18_3  \
                       mean       std  min   25%  50%   75%  max count
generation gender
Boomer     Female  4.000000  2.000000  1.0  2.75  4.0  5.00  7.0  24.0
           Male    4.250000  1.647107  1.0  3.00  4.0  6.00  7.0  28.0
Gen X      0       1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
           Female  3.700000  1.859737  1.0  2.00  4.0  5.00  7.0  30.0
           Male    4.108108  1.852682  1.0  3.00  5.0  6.00  7.0  37.0
           Null    1.000000       NaN  1.0  1.00  1.0  1.00  1.0   1.0
Gen Z      Female  4.000000  1.750000  1.0  3.00  4.0  5.00  7.0  33.0
           Male    4.444444  1.928198  1.0  3.50  5.0  5.50  7.0  27.0
           Null    4.000000       NaN  4.0  4.00  4.0  4.00  4.0   1.0
Millennial Female  4.023810  1.993823  1.0  2.00  4.0  5.25  7.0  84.0
           Male    4.387097  1.859361  1.0  3.00  5.0  6.00  7.0  93.0
Silent Gen Female  6.000000       NaN  6.0  6.00  6.0  6.00  6.0   1.0
           Male    6.000000       NaN  6.0  6.00  6.0  6.00  6.0   1.0

                                                                Q18_4  \
                       mean       std  min   25%  50%  75%  max count
generation gender
Boomer     Female  5.416667  1.501207  2.0  4.75  5.5  7.0  7.0  24.0
           Male    5.714286  1.410467  2.0  4.75  6.0  7.0  7.0  28.0
Gen X      0       5.000000       NaN  5.0  5.00  5.0  5.0  5.0   1.0
           Female  5.133333  1.479360  2.0  4.00  5.0  6.0  7.0  30.0
           Male    5.486486  1.445714  2.0  5.00  6.0  7.0  7.0  37.0
           Null    5.000000       NaN  5.0  5.00  5.0  5.0  5.0   1.0
Gen Z      Female  4.939394  1.853028  1.0  4.00  5.0  6.0  7.0  33.0
           Male    5.000000  1.493576  1.0  4.00  5.0  6.0  7.0  27.0
           Null    5.000000       NaN  5.0  5.00  5.0  5.0  5.0   1.0
Millennial Female  5.238095  1.739818  1.0  4.00  5.5  7.0  7.0  84.0
           Male    5.408602  1.562026  1.0  4.00  6.0  7.0  7.0  93.0
Silent Gen Female  7.000000       NaN  7.0  7.00  7.0  7.0  7.0   1.0
           Male    6.000000       NaN  6.0  6.00  6.0  6.0  6.0   1.0

                                                                Q18_5  \
                       mean       std  min   25%  50%  75%  max count
generation gender
Boomer     Female  4.333333  1.403928  2.0  3.00  4.0  5.0  7.0  24.0
           Male    4.714286  1.802409  1.0  4.00  5.0  6.0  7.0  28.0
Gen X      0       2.000000       NaN  2.0  2.00  2.0  2.0  2.0   1.0
           Female  4.333333  1.397864  2.0  3.25  4.0  5.0  7.0  30.0
           Male    4.243243  1.722489  1.0  4.00  4.0  5.0  7.0  37.0
           Null    3.000000       NaN  3.0  3.00  3.0  3.0  3.0   1.0
Gen Z      Female  4.454545  1.563068  1.0  4.00  5.0  5.0  7.0  33.0
           Male    4.740741  1.227649  2.0  4.00  5.0  6.0  7.0  27.0
           Null    4.000000       NaN  4.0  4.00  4.0  4.0  4.0   1.0
Millennial Female  4.809524  1.609282  1.0  4.00  5.0  6.0  7.0  84.0
           Male    4.720430  1.424671  1.0  4.00  5.0  6.0  7.0  93.0
Silent Gen Female  7.000000       NaN  7.0  7.00  7.0  7.0  7.0   1.0
           Male    5.000000       NaN  5.0  5.00  5.0  5.0  5.0   1.0

                                                               Q18_6  \
                       mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  3.875000  1.701981  1.0  2.0  4.0  5.0  7.0  24.0
           Male    4.392857  1.770944  1.0  3.0  5.0  6.0  7.0  28.0
Gen X      0       1.000000       NaN  1.0  1.0  1.0  1.0  1.0   1.0
           Female  4.400000  1.354431  2.0  4.0  4.0  5.0  7.0  30.0
           Male    4.054054  1.824919  1.0  3.0  4.0  5.0  7.0  37.0
           Null    4.000000       NaN  4.0  4.0  4.0  4.0  4.0   1.0
Gen Z      Female  4.303030  1.722731  1.0  3.0  5.0  5.0  7.0  33.0
           Male    4.037037  1.400041  2.0  3.0  4.0  5.0  7.0  27.0
           Null    4.000000       NaN  4.0  4.0  4.0  4.0  4.0   1.0
Millennial Female  4.380952  1.789560  1.0  3.0  5.0  6.0  7.0  84.0
           Male    4.537634  1.678244  1.0  3.0  5.0  6.0  7.0  93.0
Silent Gen Female  7.000000       NaN  7.0  7.0  7.0  7.0  7.0   1.0
           Male    6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0

                                                               Q18_7  \
                       mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  4.041667  1.601064  1.0  3.0  4.0  5.0  7.0  24.0
           Male    4.642857  1.768328  1.0  4.0  5.0  6.0  7.0  28.0
Gen X      0       1.000000       NaN  1.0  1.0  1.0  1.0  1.0   1.0
           Female  4.533333  1.569831  1.0  4.0  4.5  6.0  7.0  30.0
           Male    4.594595  1.623772  1.0  4.0  5.0  6.0  7.0  37.0
           Null    5.000000       NaN  5.0  5.0  5.0  5.0  5.0   1.0
Gen Z      Female  4.393939  1.784296  1.0  3.0  5.0  6.0  7.0  33.0
           Male    4.259259  1.607497  1.0  4.0  4.0  5.0  7.0  27.0
           Null    5.000000       NaN  5.0  5.0  5.0  5.0  5.0   1.0
Millennial Female  4.547619  1.792923  1.0  3.0  5.0  6.0  7.0  84.0
           Male    4.870968  1.526760  1.0  4.0  5.0  6.0  7.0  93.0
Silent Gen Female  7.000000       NaN  7.0  7.0  7.0  7.0  7.0   1.0
           Male    6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0

                                                               Q18_8  \
                       mean       std  min  25%  50%  75%  max count
generation gender
Boomer     Female  4.500000  1.744557  1.0  4.0  5.0  6.0  7.0  24.0
           Male    4.392857  2.078805  1.0  2.0  5.5  6.0  7.0  28.0
Gen X      0       6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0
           Female  4.233333  1.478194  1.0  3.0  5.0  5.0  6.0  30.0
           Male    4.108108  1.760426  1.0  3.0  4.0  5.0  7.0  37.0
           Null    5.000000       NaN  5.0  5.0  5.0  5.0  5.0   1.0
Gen Z      Female  4.151515  1.787477  1.0  3.0  4.0  6.0  7.0  33.0
           Male    4.111111  1.928198  1.0  3.0  4.0  6.0  7.0  27.0
           Null    4.000000       NaN  4.0  4.0  4.0  4.0  4.0   1.0
Millennial Female  4.333333  1.637904  1.0  4.0  4.0  5.0  7.0  84.0
           Male    4.419355  1.783515  1.0  3.0  5.0  6.0  7.0  93.0
Silent Gen Female  6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0
           Male    6.000000       NaN  6.0  6.0  6.0  6.0  6.0   1.0


                       mean       std  min   25%  50%   75%  max
generation gender
Boomer     Female  3.541667  1.864524  1.0  1.75  4.0  5.00  7.0
           Male    3.428571  1.951800  1.0  2.00  4.0  5.00  7.0
Gen X      0       3.000000       NaN  3.0  3.00  3.0  3.00  3.0
           Female  3.700000  2.086905  1.0  2.00  4.0  5.75  7.0
           Male    4.162162  1.771903  1.0  3.00  4.0  6.00  7.0
           Null    5.000000       NaN  5.0  5.00  5.0  5.00  5.0
Gen Z      Female  3.272727  1.841751  1.0  1.00  4.0  5.00  7.0
           Male    3.111111  2.207214  1.0  1.00  2.0  5.00  7.0
           Null    4.000000       NaN  4.0  4.00  4.0  4.00  4.0
Millennial Female  3.750000  2.150231  1.0  2.00  4.0  5.00  7.0
           Male    4.150538  2.095265  1.0  2.00  4.0  6.00  7.0
Silent Gen Female  5.000000       NaN  5.0  5.00  5.0  5.00  5.0
           Male    6.000000       NaN  6.0  6.00  6.0  6.00  6.0

In [47]:
# Q18_1: similarities with the following groups? - Fans of your favorite team
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_1'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.993, 4.0]                0.541667
                    (4.0, 7.0]                  0.458333
            Male    (4.0, 7.0]                  0.535714
                    (0.993, 4.0]                0.464286
Gen X       0       (0.998, 1.0]                1.000000
                    (1.0, 1.001]                0.000000
            Female  (0.993, 4.0]                0.533333
                    (4.0, 7.0]                  0.466667
            Male    (4.0, 7.0]                  0.567568
                    (0.993, 4.0]                0.432432
            Null    (0.998, 1.0]                1.000000
                    (1.0, 1.001]                0.000000
Gen Z       Female  (4.0, 7.0]                  0.636364
                    (0.993, 4.0]                0.363636
            Male    (4.0, 7.0]                  0.666667
                    (0.993, 4.0]                0.333333
            Null    (3.995, 4.0]                1.000000
                    (4.0, 4.004]                0.000000
Millennial  Female  (4.0, 7.0]                  0.559524
                    (0.993, 4.0]                0.440476
            Male    (4.0, 7.0]                  0.559140
                    (0.993, 4.0]                0.440860
Silent Gen  Female  (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
            Male    (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
Name: Q18_1, dtype: float64

In [48]:
# Q18_2: similarities with the following groups? - Fans of your favorite athletes
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_2'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.993, 4.0]                0.541667
                    (4.0, 7.0]                  0.458333
            Male    (0.993, 4.0]                0.535714
                    (4.0, 7.0]                  0.464286
Gen X       0       (0.998, 1.0]                1.000000
                    (1.0, 1.001]                0.000000
            Female  (0.993, 4.0]                0.600000
                    (4.0, 7.0]                  0.400000
            Male    (4.0, 7.0]                  0.513514
                    (0.993, 4.0]                0.486486
            Null    (0.998, 1.0]                1.000000
                    (1.0, 1.001]                0.000000
Gen Z       Female  (0.993, 4.0]                0.636364
                    (4.0, 7.0]                  0.363636
            Male    (4.0, 7.0]                  0.592593
                    (0.993, 4.0]                0.407407
            Null    (3.995, 4.0]                1.000000
                    (4.0, 4.004]                0.000000
Millennial  Female  (0.993, 4.0]                0.595238
                    (4.0, 7.0]                  0.404762
            Male    (4.0, 7.0]                  0.548387
                    (0.993, 4.0]                0.451613
Silent Gen  Female  (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
            Male    (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
Name: Q18_2, dtype: float64

In [49]:
# Q18_3: similarities with the following groups? - Family
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_3'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (4.5, 7.0]                   0.750000
                    (1.9940000000000002, 4.5]    0.250000
            Male    (4.5, 7.0]                   0.750000
                    (1.9940000000000002, 4.5]    0.250000
Gen X       0       (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
            Female  (4.5, 7.0]                   0.666667
                    (1.9940000000000002, 4.5]    0.333333
            Male    (4.5, 7.0]                   0.783784
                    (1.9940000000000002, 4.5]    0.216216
            Null    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Gen Z       Female  (4.0, 7.0]                   0.666667
                    (0.993, 4.0]                 0.333333
            Male    (4.0, 7.0]                   0.592593
                    (0.993, 4.0]                 0.407407
            Null    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Millennial  Female  (4.0, 7.0]                   0.702381
                    (0.993, 4.0]                 0.297619
            Male    (4.0, 7.0]                   0.731183
                    (0.993, 4.0]                 0.268817
Silent Gen  Female  (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Male    (5.992999999999999, 6.0]     1.000000
                    (6.0, 6.006]                 0.000000
Name: Q18_3, dtype: float64

In [50]:
# Q18_4: similarities with the following groups? - Gender
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_4'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (1.9940000000000002, 4.5]    0.583333
                    (4.5, 7.0]                   0.416667
            Male    (4.0, 7.0]                   0.642857
                    (0.993, 4.0]                 0.357143
Gen X       0       (1.997, 2.0]                 1.000000
                    (2.0, 2.002]                 0.000000
            Female  (1.9940000000000002, 4.5]    0.533333
                    (4.5, 7.0]                   0.466667
            Male    (0.993, 4.0]                 0.513514
                    (4.0, 7.0]                   0.486486
            Null    (2.996, 3.0]                 1.000000
                    (3.0, 3.003]                 0.000000
Gen Z       Female  (4.0, 7.0]                   0.545455
                    (0.993, 4.0]                 0.454545
            Male    (4.5, 7.0]                   0.518519
                    (1.9940000000000002, 4.5]    0.481481
            Null    (3.995, 4.0]                 1.000000
                    (4.0, 4.004]                 0.000000
Millennial  Female  (4.0, 7.0]                   0.583333
                    (0.993, 4.0]                 0.416667
            Male    (4.0, 7.0]                   0.559140
                    (0.993, 4.0]                 0.440860
Silent Gen  Female  (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Male    (4.994, 5.0]                 1.000000
                    (5.0, 5.005]                 0.000000
Name: Q18_4, dtype: float64

In [51]:
# Q18_5: similarities with the following groups? - Racial group
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_5'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.993, 4.0]                 0.666667
                    (4.0, 7.0]                   0.333333
            Male    (4.0, 7.0]                   0.571429
                    (0.993, 4.0]                 0.428571
Gen X       0       (0.998, 1.0]                 1.000000
                    (1.0, 1.001]                 0.000000
            Female  (1.9940000000000002, 4.5]    0.533333
                    (4.5, 7.0]                   0.466667
            Male    (0.993, 4.0]                 0.594595
                    (4.0, 7.0]                   0.405405
            Null    (3.995, 4.0]                 1.000000
                    (4.0, 4.004]                 0.000000
Gen Z       Female  (4.0, 7.0]                   0.515152
                    (0.993, 4.0]                 0.484848
            Male    (1.9940000000000002, 4.5]    0.703704
                    (4.5, 7.0]                   0.296296
            Null    (3.995, 4.0]                 1.000000
                    (4.0, 4.004]                 0.000000
Millennial  Female  (4.0, 7.0]                   0.535714
                    (0.993, 4.0]                 0.464286
            Male    (4.0, 7.0]                   0.526882
                    (0.993, 4.0]                 0.473118
Silent Gen  Female  (6.992, 7.0]                 1.000000
                    (7.0, 7.007]                 0.000000
            Male    (5.992999999999999, 6.0]     1.000000
                    (6.0, 6.006]                 0.000000
Name: Q18_5, dtype: float64

In [52]:
# Q18_6: similarities with the following groups? - Nationality
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_6'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.993, 4.0]                0.666667
                    (4.0, 7.0]                  0.333333
            Male    (4.0, 7.0]                  0.607143
                    (0.993, 4.0]                0.392857
Gen X       0       (0.998, 1.0]                1.000000
                    (1.0, 1.001]                0.000000
            Female  (0.993, 4.0]                0.500000
                    (4.0, 7.0]                  0.500000
            Male    (4.0, 7.0]                  0.540541
                    (0.993, 4.0]                0.459459
            Null    (4.994, 5.0]                1.000000
                    (5.0, 5.005]                0.000000
Gen Z       Female  (4.0, 7.0]                  0.545455
                    (0.993, 4.0]                0.454545
            Male    (0.993, 4.0]                0.592593
                    (4.0, 7.0]                  0.407407
            Null    (4.994, 5.0]                1.000000
                    (5.0, 5.005]                0.000000
Millennial  Female  (4.0, 7.0]                  0.583333
                    (0.993, 4.0]                0.416667
            Male    (4.0, 7.0]                  0.602151
                    (0.993, 4.0]                0.397849
Silent Gen  Female  (6.992, 7.0]                1.000000
                    (7.0, 7.007]                0.000000
            Male    (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
Name: Q18_6, dtype: float64

In [53]:
# Q18_7: similarities with the following groups? - Political ideology
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_7'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (4.0, 7.0]                  0.541667
                    (0.993, 4.0]                0.458333
            Male    (4.0, 7.0]                  0.571429
                    (0.993, 4.0]                0.428571
Gen X       0       (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
            Female  (3.5, 6.0]                  0.700000
                    (0.994, 3.5]                0.300000
            Male    (0.993, 4.0]                0.567568
                    (4.0, 7.0]                  0.432432
            Null    (4.994, 5.0]                1.000000
                    (5.0, 5.005]                0.000000
Gen Z       Female  (0.993, 4.0]                0.545455
                    (4.0, 7.0]                  0.454545
            Male    (0.993, 4.0]                0.629630
                    (4.0, 7.0]                  0.370370
            Null    (3.995, 4.0]                1.000000
                    (4.0, 4.004]                0.000000
Millennial  Female  (0.993, 4.0]                0.559524
                    (4.0, 7.0]                  0.440476
            Male    (4.0, 7.0]                  0.516129
                    (0.993, 4.0]                0.483871
Silent Gen  Female  (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
            Male    (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
Name: Q18_7, dtype: float64

In [54]:
# Q18_8: similarities with the following groups? - Religion or faith
sports_fan_demographics.groupby(['generation', 'gender'])['Q18_8'].value_counts(sort=True, normalize=True, bins=2)

generation  gender
Boomer      Female  (0.993, 4.0]                0.666667
                    (4.0, 7.0]                  0.333333
            Male    (0.993, 4.0]                0.642857
                    (4.0, 7.0]                  0.357143
Gen X       0       (2.996, 3.0]                1.000000
                    (3.0, 3.003]                0.000000
            Female  (0.993, 4.0]                0.566667
                    (4.0, 7.0]                  0.433333
            Male    (0.993, 4.0]                0.540541
                    (4.0, 7.0]                  0.459459
            Null    (4.994, 5.0]                1.000000
                    (5.0, 5.005]                0.000000
Gen Z       Female  (0.993, 4.0]                0.727273
                    (4.0, 7.0]                  0.272727
            Male    (0.993, 4.0]                0.703704
                    (4.0, 7.0]                  0.296296
            Null    (3.995, 4.0]                1.000000
                    (4.0, 4.004]                0.000000
Millennial  Female  (0.993, 4.0]                0.630952
                    (4.0, 7.0]                  0.369048
            Male    (0.993, 4.0]                0.559140
                    (4.0, 7.0]                  0.440860
Silent Gen  Female  (4.994, 5.0]                1.000000
                    (5.0, 5.005]                0.000000
            Male    (5.992999999999999, 6.0]    1.000000
                    (6.0, 6.006]                0.000000
Name: Q18_8, dtype: float64

## Indiviudal Sports

In [ ]:
sports_individuals_sports = sports_v2.loc[:, ['Q28#1_1','Q28#1_2','Q28#1_3','Q28#1_4','Q28#1_5','Q28#1_6','Q28#1_7','Q28#1_8','Q28#1_9','Q28#1_10','Q28#1_11','Q28#1_12','Q28#1_13','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [ ]:
# Q28#1_1: Are you a fan of LeBron James (NBA)
# Q28#1_2: Are you a fan of Mike Trout (MLB)
# Q28#1_3: Are you a fan of Patrick Mahomes (NFL)
# Q28#1_4: Are you a fan of Luca Doncic (NBA)
# Q28#1_5: Are you a fan of Colin Kaepernick (NFL & Social Activist)
# Q28#1_6: Are you a fan of Cristiano Ronaldo (Soccer)
# Q28#1_7: Are you a fan of Serena Williams (Tennis)
# Q28#1_8: Are you a fan of Roger Federer (Tennis)
# Q28#1_9: Are you a fan of Megan Rapinoe (Soccer)
# Q28#1_10: Are you a fan of  Michael Jordan (NBA)
# Q28#1_11: Are you a fan of Tiger Woods (Golf)
# Q28#1_12: Are you a fan of Conor McGregor (Martial Arts)
# Q28#1_13: Are you a fan of Mike Tyson (Boxing)
sports_individuals_sports.groupby(["generation", "gender"]).describe()

## Individual Music

In [ ]:
sports_individuals_music = sports_v2.loc[:, ['Q28#1_14','Q28#1_15','Q28#1_16','Q28#1_17','Q28#1_18','Q28#1_19','Q28#1_20','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [ ]:
# Q28#1_14: Are you a fan of Taylor Swift (Music)
# Q28#1_15: Are you a fan of Beyonce (Music)
# Q28#1_16: Are you a fan of Bruce Springsteen (Music)
# Q28#1_17: Are you a fan of Drake (Music)
# Q28#1_18: Are you a fan of Ariana Grande (Music)
# Q28#1_19: Are you a fan of Cardi B (Music)
# Q28#1_20: Are you a fan of BTS (Music)
sports_individuals_music.groupby(["generation", "gender"]).describe()

## Individual Movie

In [ ]:
sports_individuals_movie = sports_v2.loc[:, ['Q28#1_21','Q28#1_22','Q28#1_23','Q28#1_24','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [ ]:
# Q28#1_21: Are you a fan of Tom Cruise (Movies)
# Q28#1_22: Are you a fan of Gal Gadot (Movies)
# Q28#1_23: Are you a fan of The Rock (Movies)
# Q28#1_24: Are you a fan of Jennifer Aniston (Movies)
sports_individuals_movie.groupby(["generation", "gender"]).describe()

# Individual SNS

In [ ]:
sports_individuals_sns = sports_v2.loc[:, ['Q28#1_26','Q28#1_27','Q28#1_28','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [ ]:
# Are you a fan of PewDiePie (YouTube)
# Are you a fan of Charli D'Amelio (TikTok)
# Are you a fan of Kylie Jenner (IG)
sports_individuals_sns.groupby(["generation", "gender"]).describe()

## Individual Politics

In [ ]:
sports_individuals_politics = sports_v2.loc[:, ['Q28#1_29','Q28#1_30','generation','gender', 'race', 'SES', 'political_spectrum', 'religious_spectrum', 'nationality']]

In [ ]:
# Are you a fan of Bernie Sanders (Politician)
# Are you a fan of Donald Trump (Politician)
sports_individuals_politics.groupby(["generation", "gender"]).describe()

## Export it to .csv file

In [ ]:
#sports_fandom.to_csv('sports_fandom.csv', encoding='utf-8', index=False)
#sports_fans.to_csv('sports_fans.csv', encoding='utf-8', index=False)
#sports_fan_demographics.to_csv('fan_demographics.csv', encoding='utf-8', index=False)
#sports_individuals_sports.to_csv('individual_sports.csv', encoding='utf-8', index=False)
#sports_individuals_music.to_csv('individual_music.csv', encoding='utf-8', index=False)
#sports_individuals_movie.to_csv('individual_movie.csv', encoding='utf-8', index=False)
#sports_individuals_sns.to_csv('individual_sns.csv', encoding='utf-8', index=False)
#sports_individuals_politics.to_csv('individual_politics.csv', encoding='utf-8', index=False)